package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.triggers.vcs
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'SystemTestLatestRelease'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    templates(RelativeId("WflowSystemTestTemplate"), RelativeId("GitHubPrTemplate"), RelativeId("WflowWindowsAgentTemplate"))
    id("SystemTestLatestRelease")
    name = "System test (latest release)"
    description = "Runs system test using the latest release build of wflow.jl"

    params {
        text("status.check.name", "System test (Wflow-dev)", allowEmpty = false)
        text("wflow.cli.branch.filter", "+:release/v1.0", description = "Newline-delimited set of rules in the form of +|-:logical branch name (with an optional * placeholder)", allowEmpty = false)
    }

    vcs {
        root(RelativeId("WflowJl"))
    }

    triggers {
        vcs {
            id = "TRIGGER_862"
            branchFilter = """
                +:refs/heads/master
                +:refs/tags/*
            """.trimIndent()
        }
    }
}))

