package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'SystemTestDev'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("SystemTestDev")) {
    dependencies {
        expect(AbsoluteId("wflow_BuildWflowCliWindows")) {
            snapshot {
                onDependencyFailure = FailureAction.FAIL_TO_START
            }

            artifacts {
                id = "ARTIFACT_DEPENDENCY_7064"
                buildRule = sameChain()
                cleanDestination = true
                artifactRules = """+:wflow_cli.zip!/wflow_cli/** => %teamcity.agent.work.dir%\wflow_cli"""
            }
        }
        update(AbsoluteId("wflow_BuildWflowCliWindows")) {
            artifacts {
                id = "ARTIFACT_DEPENDENCY_7064"
                buildRule = lastSuccessful()
                cleanDestination = true
                artifactRules = """+:wflow_cli.zip!/wflow_cli/** => %teamcity.agent.work.dir%\wflow_cli"""
            }
        }

    }
}
