dir_output = "run_default"

[time]
calendar = "proleptic_gregorian"
starttime = "2010-02-01T00:00:00"
endtime = "2010-02-10T00:00:00"
time_units = "days since 1900-01-01 00:00:00"
timestepsecs = 86400

[logging]
loglevel = "info"

[model]
type = "sediment"
reinit = true
run_river_model = true
rainfall_erosion = "answers"
overland_flow_erosion = "answers"
land_transport = "yalinpart"
river_transport = "bagnold"
reservoirs = true
lakes = true

[state]
path_input = "instate/instates.nc"
path_output = "outstate/outstates.nc"

[input]
path_forcing = "inmaps.nc"
path_static = "staticmaps.nc"
local_drain_direction = "wflow_ldd"
subcatchment_location__count = "wflow_subcatch"
river_location__mask = "wflow_river"
reservoir_area__count = "wflow_reservoirareas"
reservoir_location__count = "wflow_reservoirlocs"
lake_area__count = "wflow_lakeareas"
lake_location__count = "wflow_lakelocs"
gauges = "wflow_gauges"
gauges_grdc = "wflow_gauges_grdc"

[state.variables]
river_water_clay__mass = "clayload"
river_bed_clay__mass = "claystore"
river_water_gravel__mass = "gravload"
river_bed_gravel__mass = "gravstore"
"river_water_aggregates~large__mass" = "laggload"
"river_bed_aggregates~large__mass" = "laggstore"
river_water_clay__mass_flow_rate = "outclay"
river_water_gravel__mass_flow_rate = "outgrav"
"river_water_aggregates~large__mass_flow_rate" = "outlagg"
"river_water_aggregates~small__mass_flow_rate" = "outsagg"
river_water_sand__mass_flow_rate = "outsand"
river_water_silt__mass_flow_rate = "outsilt"
"river_water_aggregates~small__mass" = "saggload"
"river_bed_aggregates~small__mass" = "saggstore"
river_water_sand__mass = "sandload"
river_bed_sand__mass = "sandstore"
river_water_silt__mass = "siltload"
river_bed_silt__mass = "siltstore"

[input.forcing]
atmosphere_water__precipitation_volume_flux = "precip"
vegetation_canopy_water__interception_volume_flux = "vegetation_interception"
land_surface_water__depth = "land_h"
land_surface_water__volume_flow_rate = "land_q"
river_water__depth = "river_h"
river_water__volume_flow_rate = "river_q"

[input.static]
land_surface__slope = "land_slope"
river__length = "river_length"
river__slope = "river_slope"
river__width = "river_width"
reservoir_surface__area = "reservoir_area"
"reservoir_sediment~bedload__trapping_efficiency_coefficient" = "reservoir_trapping_efficiency"
lake_surface__area = "lake_area"
river_bottom-and-bank_sediment__d50_diameter = "D50_River"
river_bottom-and-bank_clay__mass_fraction = "ClayF_River"
river_bottom-and-bank_silt__mass_fraction = "SiltF_River"
river_bottom-and-bank_sand__mass_fraction = "SandF_River"
river_bottom-and-bank_gravel__mass_fraction = "GravelF_River"
river_water_sediment__kodatie_transport_capacity_a-coefficient = "a_kodatie"
river_water_sediment__kodatie_transport_capacity_b-coefficient = "b_kodatie"
river_water_sediment__kodatie_transport_capacity_c-coefficient = "c_kodatie"
river_water_sediment__kodatie_transport_capacity_d-coefficient = "d_kodatie"
"soil~compacted__area_fraction" = "PathFrac"
soil_erosion__usle_c_factor = "erosion_usle_c "
"land~water-covered__area_fraction" = "WaterFrac"
vegetation_canopy__height = "vegetation_height"
soil_erosion__rainfall_soil_detachability_factor = erosion_soil_detachability"
soil_erosion__usle_k_factor = "erosion_usle_k"
land_surface_sediment__d50_diameter = "soil_sediment_d50"
land_surface_water_sediment__govers_transport_capacity_coefficient = "c_govers"
land_surface_water_sediment__govers_transport_capacity_exponent = "n_govers"
soil_clay__mass_fraction = "soil_clay_fraction"
soil_silt__mass_fraction = "soil_silt_fraction"
"soil_aggregates~small__mass_fraction" = "soil_sagg_fraction"
soil_sand__mass_fraction = "soil_sand_fraction"
"soil_aggregates~large__mass_fraction" = "soil_lagg_fraction"

[output.netcdf_grid]
path = "output.nc"
compressionlevel = 1

[output.csv]
path = "output.csv"
[[output.csv.column]]
header = "TSS"
map = "gauges"
parameter = "river_water_sediment~suspended__mass_concentration"

[[output.csv.column]]
header = "Q"
map = "gauges_grdc"
parameter = "river_water__volume_flow_rate"

[[output.csv.column]]
header = "TSS"
map = "gauges_grdc"
parameter = "river_water_sediment~suspended__mass_concentration"

[input.static.land_surface_sediment__particle_density]
value = 2650

[input.static.clay__d50_diameter]
value = 2

[input.static.silt__d50_diameter]
value = 10

[input.static."sediment_aggregates~small__d50_diameter"]
value = 30

[input.static.sand__d50_diameter]
value = 200

[input.static."sediment_aggregates~large__d50_diameter"]
value = 500

[input.static.gravel__d50_diameter]
value = 2000

[input.static.river_water_sediment__bagnold_transport_capacity_coefficient]
value = 1.75e-5

[input.static.soil_erosion__answers_overland_flow_factor]
value = 0.9

[input.static.soil_erosion__eurosem_exponent]
value = 2.0

[input.static.river_water_sediment__bagnold_transport_capacity_exponent]
value = 1.4

[output.netcdf_grid.variables]
soil_erosion__mass_flow_rate = "soil_loss"
"river_water_sediment~suspended__mass_concentration" = "TSS"
