package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    params {
        add {
            password("env.earthdatahub.apikey", "credentialsJSON:6c0dcda0-ac7a-4304-915f-566fb8b37b54", description = "api key generated at 28/7 using luuk.blom@deltares.nl and https://earthdatahub.destine.eu/getting-started#configuring-netrc", display = ParameterDisplay.HIDDEN, readOnly = true)
        }
    }
}
