dir_output = "run_default"

[time]
calendar     = "proleptic_gregorian"
time_units   = "days since 1900-01-01 00:00:00"
timestepsecs = 86400
starttime = "2010-02-02T00:00:00"
endtime = "2010-02-10T00:00:00"

[logging]
loglevel = "info"

[model]
type                                    = "sbm"
snow_gravitational_transport__flag      = true
snow__flag                              = true
cold_start__flag                        = true
kinematic_wave__adaptive_time_step_flag = true
river_kinematic_wave__time_step         = 900
land_kinematic_wave__time_step          = 3600
river_routing = "kinematic-wave"
glacier__flag = true
soil_layer__thickness = [100, 300, 800]
reservoir__flag = false

[state]
path_input  = "instate/instates.nc"
path_output = "outstate/outstates.nc"

[state.variables]
vegetation_canopy_water__depth                     = "vegetation_water_depth"
soil_water_sat-zone__depth                         = "soil_saturated_depth"
soil_layer_water_unsat-zone__depth                 = "soil_unsaturated_depth"
soil_surface__temperature                          = "soil_temp"
"snowpack~dry__leq-depth"                          = "snow_leq_depth"
"snowpack~liquid__depth"                           = "snow_water_depth"
land_surface_water__instantaneous_volume_flow_rate = "land_instantaneous_q"
land_surface_water__instantaneous_depth            = "land_instantaneous_h"
subsurface_water__volume_flow_rate                 = "subsurface_q"
river_water__instantaneous_volume_flow_rate        = "river_instantaneous_q"
river_water__instantaneous_depth                   = "river_instantaneous_h"
glacier_ice__leq-depth = "glacier_leq_depth"

[input]
path_forcing = "inmaps.nc"
basin__local_drain_direction = "local_drain_direction"
subbasin_location__count = "subcatchment"
river_location__mask = "river_mask"
outlets = "outlets"
gauges_grdc = "gauges_grdc"
path_static = "staticmaps.nc"

[input.forcing]
atmosphere_water__precipitation_volume_flux = "precip"
land_surface_water__potential_evaporation_volume_flux = "pet"
atmosphere_air__temperature = "temp"

[input.cyclic]
vegetation__leaf-area_index = "vegetation_leaf_area_index"

[input.static]
land_surface__slope = "land_slope"
river__length = "river_length"
river__slope = "river_slope"
river_water_flow__manning_n_parameter = "river_manning_n"
river__width = "river_width"
river_bank_water__depth = "river_depth"
glacier_ice__initial_leq-depth = "glacier_initial_leq_depth"
glacier_surface__area_fraction = "glacier_fraction"
vegetation_canopy__light-extinction_coefficient = "vegetation_kext"
land_surface_water_flow__manning_n_parameter = "land_manning_n"
"soil~compacted__area_fraction" = "soil_compacted_fraction"
vegetation_root__depth = "vegetation_root_depth"
vegetation__specific-leaf_storage = "vegetation_leaf_storage"
vegetation_wood_water__storage_capacity = "vegetation_wood_storage"
"land~water-covered__area_fraction" = "land_water_fraction"
vegetation__crop_factor = "vegetation_crop_factor"
"vegetation_root__feddes_critial_pressure_head_h~1_reduction_coefficient" = "vegetation_feddes_alpha_h1"
"vegetation_root__feddes_critial_pressure_head_h~1" = "vegetation_feddes_h1"
"vegetation_root__feddes_critial_pressure_head_h~2" = "vegetation_feddes_h2"
"vegetation_root__feddes_critial_pressure_head_h~3~high" = "vegetation_feddes_h3_high"
"vegetation_root__feddes_critial_pressure_head_h~3~low" = "vegetation_feddes_h3_low"
"vegetation_root__feddes_critial_pressure_head_h~4" = "vegetation_feddes_h4"
soil_water__saturated_volume_fraction = "soil_theta_s"
soil_water__residual_volume_fraction = "soil_theta_r"
soil__thickness = "soil_thickness"
soil_layer_water__brooks-corey_exponent = "soil_brooks_corey_c"
soil_surface_water__vertical_saturated_hydraulic_conductivity = "soil_ksat_vertical"
soil_water__vertical_saturated_hydraulic_conductivity_scale_parameter = "soil_f"
subsurface_water__horizontal-to-vertical_saturated_hydraulic_conductivity_ratio.value = 100
snowpack__degree-day_coefficient.value = 3.75653
soil_surface_water__infiltration_reduction_parameter.value = 0.038
vegetation_canopy_water__mean_evaporation-to-mean_precipitation_ratio.value = 0.11
"soil~compacted_surface_water__infiltration_capacity".value = 5
soil_water_sat-zone_bottom__max_leakage_volume_flux.value = 0
"soil_root~wet__sigmoid_function_shape_parameter".value = -500
atmosphere_air__snowfall_temperature_threshold.value = 0
atmosphere_air__snowfall_temperature_interval.value = 2
snowpack__melting_temperature_threshold.value = 0
snowpack__liquid_water_holding_capacity.value = 0.1
glacier_ice__degree-day_coefficient.value = 5.3
"glacier_firn_accumulation__snowpack~dry_leq-depth_fraction".value = 0.002
glacier_ice__melting_temperature_threshold.value = 1.3

[output.netcdf_grid]
path = "output.nc"
compressionlevel = 1

[output.netcdf_grid.variables]
river_water__volume_flow_rate = "river_q"

[output.csv]
path = "output.csv"

[[output.csv.column]]
header = "river_q"
map = "outlets"
parameter = "river_water__volume_flow_rate"

[[output.csv.column]]
header = "river_q"
map = "gauges_grdc"
parameter = "river_water__volume_flow_rate"

[[output.csv.column]]
header = "precip"
map = "gauges_grdc"
parameter = "atmosphere_water__precipitation_volume_flux"

[output.netcdf_scalar]
