package patches.templates

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the template with id = 'WflowSystemTestTemplate'
accordingly, and delete the patch script.
*/
changeTemplate(RelativeId("WflowSystemTestTemplate")) {
    params {
        remove {
            text("wflow.cli.version.latest", "v1.1.0",
                  regex = """^v\d+\.\d+\.\d+${'$'}""", validationMessage = "Must be a valid 'vx.y.z' version (for example, v1.1.0)")
        }
    }
}
