## Build a Wflow model from scratch

This notebook demonstrates how to prepare **Wflow** model from scratch using the command line interace (CLI).

All lines in this notebook which start with `!` are executed from the command line. Within the notebook environment the logging messages are shown after completion. You can also copy these lines and paste these in your shell to get more direct feedback.

### hydroMT CLI build interface

Lets first check if the Wflow model is recognized by hydromt

In [1]:
# this should return "wflow, wflow_seciment"
!hydromt --models

hydroMT model plugins: wflow (v0.1.4.dev0), wflow_sediment (v0.1.4.dev0)


Using the **hydromt build** API we can setup a complete model from scratch. Let's get an overview of all the available options:

In [2]:
!hydromt build --help

Usage: hydromt build [OPTIONS] MODEL MODEL_ROOT REGION

  Build models from source data.

  Example usage:
  --------------

  To build a wflow model for a subbasin using and point coordinates snapped to cells with stream order >= 4
  hydromt build wflow /path/to/model_root "{'subbasin': [-7.24, 62.09], 'strord': 4}" -i /path/to/wflow_config.ini

  To build a wflow model based on basin ID
  hydromt build wflow /path/to/model_root "{'basin': 230001006}"

  To build a sfincs model based on a bbox (for Texel)
  hydromt build sfincs /path/to/model_root "{'bbox': [4.6891,52.9750,4.9576,53.1994]}"

Options:
  -r, --res FLOAT             Model resolution in model src.
  --build-base / --build-all  Deprecated!
  --opt TEXT                  Component specific keyword arguments, see the
                              setup_<component> method of the specific model
                              for more information about the arguments.
  -i, --config PATH           Path to hydroMT configuration fil

### setup wflow model base layers 

In [3]:
# NOTE: copy this line (without !) to your shell for more direct feedback
!hydromt build wflow "./wflow_test_base" "{'subbasin': [12.2051, 45.8331], 'strord': 4, 'bounds': [11.70, 45.35, 12.95, 46.70]}" -r 0.00833 -v

2022-02-15 16:11:37,714 - build - log - INFO - HydroMT version: 0.4.5.dev
2022-02-15 16:11:37,714 - build - main - INFO - Building instance of wflow model at /home/runner/work/hydromt_wflow/hydromt_wflow/docs/examples/examples/wflow_test_base.
2022-02-15 16:11:37,714 - build - main - INFO - User settings:


2022-02-15 16:11:37,720 - build - model_api - INFO - Initializing wflow model from hydromt_wflow (v0.1.4.dev0).
2022-02-15 16:11:37,720 - build - model_api - INFO - setup_basemaps.region: {'subbasin': [12.2051, 45.8331], 'strord': 4, 'bounds': [11.7, 45.35, 12.95, 46.7]}
2022-02-15 16:11:37,720 - build - model_api - INFO - setup_basemaps.res: 0.00833
2022-02-15 16:11:37,720 - build - model_api - INFO - setup_basemaps.hydrography_fn: merit_hydro
2022-02-15 16:11:37,720 - build - model_api - INFO - setup_basemaps.basin_index_fn: merit_hydro_index
2022-02-15 16:11:37,721 - build - model_api - INFO - setup_basemaps.upscale_method: ihu
2022-02-15 16:11:37,721 - build - wflow - INFO - Preparing base hydrography basemaps.


2022-02-15 16:11:37,965 - build - data_adapter - INFO - Downloading file to /home/runner/.hydromt_data/data/v0.0.6/data.tar.gz


2022-02-15 16:11:39,136 - build - data_adapter - INFO - Adding sample data v0.0.6 from artifacts


2022-02-15 16:11:39,195 - build - data_adapter - INFO - DataCatalog: Getting merit_hydro RasterDataset raster data from /home/runner/.hydromt_data/data/v0.0.6/merit_hydro/{variable}.tif


2022-02-15 16:11:42,983 - build - basin_mask - INFO - subbasin bbox: [11.7750, 45.8042, 12.7450, 46.6900]


2022-02-15 16:11:43,403 - build - basemaps - INFO - Upscale flow direction data: 10x, ihu method.


2022-02-15 16:11:57,984 - build - wflow - INFO - Write model data to /home/runner/work/hydromt_wflow/hydromt_wflow/docs/examples/examples/wflow_test_base
2022-02-15 16:11:57,987 - build - model_api - INFO - Writing model config to /home/runner/work/hydromt_wflow/hydromt_wflow/docs/examples/examples/wflow_test_base/wflow_sbm.toml
2022-02-15 16:11:57,988 - build - wflow - INFO - Write staticmaps to /home/runner/work/hydromt_wflow/hydromt_wflow/docs/examples/examples/wflow_test_base/staticmaps.nc


2022-02-15 16:11:58,185 - build - wflow - INFO - Writing model staticgeom to file.


The example above means the following: run **hydromt build** with:

* `wflow` : i.e. build a wflow model
* `./wflow_test_base` : output model folder
* `"{'subbasin': [12.2051, 45.8331], 'strord': 4, 'bounds': [11.70, 45.35, 12.95, 46.70]}"` : derive a subbasin with its outlet at the given x,y coordinates and within the given bounds [xmin, ymin, xmax, ymax] (WGS84) snapped to a river with minimum stream order (strord) of 4. All *REGION* options are described in the [docs](https://deltares.github.io/hydromt/latest/user_guide/cli.html#region-options)
* `-r 0.0083333` : build the model at a 30 arc sec (~1km) resolution
* `-vv` : give some extra verbosity (2 * v) to display feedback on screen. Now debug messages are provided.

NOTE: As we did not specify a model configuration, only the base maps (topography and hydrography) have been setup using default parameters. To build a complete model we need the use a configuraton ini-file.

### Model setup configuration

The ini-file contains the model setup configuration and determines which components are build and in which order and optionally sets non-default arguments for each component. This configuration is passed to hydromt using `-i <path_to_ini_file>`. We have prepared several example ini-files which are available in the model repository [examples folder](https://github.com/Deltares/hydromt_wflow/tree/main/examples) and from the [docs(build_configuration)](https://deltares.github.io/hydromt_wflow/latest/user_guide/wflow/build_configuration.html). 

Each header as shown between `[...]` (e.g. `[setup_basemaps]`) corresponds to a model component. All model components are explained in the [docs(model_components)](https://deltares.github.io/hydromt_wflow/latest/user_guide/wflow/components.html). 

We will load the default wflow build ini file for inspection:

In [4]:
fn_ini = "wflow_build.ini"
with open(fn_ini, "r") as f:
    txt = f.read()
print(txt)

[global]
data_libs       = []            # add optional paths to data yml files

[setup_config]                  # options parsed to wflow ini file <section>.<option>
starttime = 2010-01-01T00:00:00
endtime = 2010-03-31T00:00:00
timestepsecs = 86400
input.path_forcing = inmaps-era5-2010.nc

[setup_basemaps]
hydrography_fn     = merit_hydro   # source hydrography data {merit_hydro, merit_hydro_1k}
basin_index_fn  = merit_hydro_index # source of basin index corresponding to hydrography_fn
upscale_method  = ihu           # upscaling method for flow direction data, by default 'ihu'

[setup_rivers]
hydrography_fn   = merit_hydro      # source hydrography data, should correspond to hydrography_fn in setup_basemaps
river_geom_fn    = rivers_lin2019_v1 # river source data with river width and bankfull discharge
river_upa        = 30               # minimum upstream area threshold for the river map [km2]
rivdph_method    = powlaw           # method to estimate depth {'powlaw', 'manning', 'gvf'}

### Data for model setup

The `<...>_fn` arguments correspond to a data source from the `DataCatalog` which is based on a yml-file with references to the data paths/urls and how the data should be read. This file can be provided to hydromt using `-d <path_to_yml_file>`. 

By default some example data for the Piave basin will be downloaded to `~/.hydromt_data/` which is also used for this example. An overview of the available example data is provided [here](https://deltares.github.io/hydromt/latest/user_guide/data.html#available-global-datasets)
This example data is a based on the data which available from the Deltares p-drive. 
If you have acces to this drive, a pre-configured catalog file can be loaded using the `--dd` flag. 

More background how to write a data catalog yml file can be found in the [hydromt core docs](https://deltares.github.io/hydromt/latest/user_guide/data.html) 

### Setup complete wflow model 

In [5]:
# NOTE: copy this line (without !) to your shell for more direct feedback
!hydromt build wflow "./wflow_test_full" "{'subbasin': [12.2051, 45.8331], 'strord': 4, 'bounds': [11.70, 45.35, 12.95, 46.70]}" -r 0.00833 -i wflow_build.ini -vv

2022-02-15 16:12:02,003 - build - log - DEBUG - Writing log messages to new file /home/runner/work/hydromt_wflow/hydromt_wflow/docs/examples/examples/wflow_test_full/hydromt.log.
2022-02-15 16:12:02,003 - build - log - INFO - HydroMT version: 0.4.5.dev
2022-02-15 16:12:02,003 - build - main - INFO - Building instance of wflow model at /home/runner/work/hydromt_wflow/hydromt_wflow/docs/examples/examples/wflow_test_full.
2022-02-15 16:12:02,003 - build - main - INFO - User settings:
2022-02-15 16:12:02,012 - build - model_plugins - DEBUG - Loaded model plugin 'wflow = hydromt_wflow.wflow.WflowModel' (0.1.4.dev0)
2022-02-15 16:12:02,013 - build - model_api - INFO - Initializing wflow model from hydromt_wflow (v0.1.4.dev0).
2022-02-15 16:12:02,013 - build - model_api - DEBUG - Setting model config options.
2022-02-15 16:12:02,015 - build - model_api - DEBUG - Default config read from /usr/share/miniconda/envs/hydromt-wflow/lib/python3.9/site-packages/hydromt_wflow/data/wflow/wflow_sbm.toml

2022-02-15 16:12:02,082 - build - data_adapter - INFO - DataCatalog: Getting merit_hydro RasterDataset raster data from /home/runner/.hydromt_data/data/v0.0.6/merit_hydro/{variable}.tif


2022-02-15 16:12:02,164 - build - basin_mask - DEBUG - Parsed region (kind=subbasin): {'strord': 4, 'bounds': [11.7, 45.35, 12.95, 46.7], 'xy': [12.2051, 45.8331]}


2022-02-15 16:12:06,034 - build - basin_mask - INFO - subbasin bbox: [11.7750, 45.8042, 12.7450, 46.6900]


2022-02-15 16:12:06,106 - build - wflow - DEBUG - Adding basins vector to staticgeoms.
2022-02-15 16:12:06,106 - build - basemaps - DEBUG - Mask in dataset assumed to represent subbasins.
2022-02-15 16:12:06,108 - build - basemaps - DEBUG - (Sub)basin at original resolution has 664756 cells.


2022-02-15 16:12:06,348 - build - basemaps - DEBUG - Burn subbasin outlet in upstream area data.


2022-02-15 16:12:06,452 - build - basemaps - INFO - Upscale flow direction data: 10x, ihu method.


2022-02-15 16:12:20,847 - build - basemaps - DEBUG - Derive stream order.


2022-02-15 16:12:21,075 - build - basemaps - DEBUG - Map shape: (106, 116); active cells: 6637.
2022-02-15 16:12:21,076 - build - basemaps - DEBUG - Outlet coordinates (1/1): (12.20750,45.83583).


2022-02-15 16:12:21,132 - build - wflow - DEBUG - Adding region vector to staticgeoms.
2022-02-15 16:12:21,136 - build - model_api - INFO - setup_rivers.hydrography_fn: merit_hydro
2022-02-15 16:12:21,136 - build - model_api - INFO - setup_rivers.river_geom_fn: rivers_lin2019_v1
2022-02-15 16:12:21,136 - build - model_api - INFO - setup_rivers.river_upa: 30
2022-02-15 16:12:21,137 - build - model_api - INFO - setup_rivers.rivdph_method: powlaw
2022-02-15 16:12:21,137 - build - model_api - INFO - setup_rivers.slope_len: 2000
2022-02-15 16:12:21,137 - build - model_api - INFO - setup_rivers.min_rivlen_ratio: 0.1
2022-02-15 16:12:21,137 - build - model_api - INFO - setup_rivers.min_rivdph: 1
2022-02-15 16:12:21,137 - build - model_api - INFO - setup_rivers.min_rivwth: 30
2022-02-15 16:12:21,137 - build - model_api - INFO - setup_rivers.smooth_len: 5000
2022-02-15 16:12:21,137 - build - model_api - INFO - setup_rivers.rivman_mapping_fn: /usr/share/miniconda/envs/hydromt-wflow/lib/python3.9

2022-02-15 16:12:21,196 - build - data_adapter - DEBUG - RasterDataset: Clip with geom - [11.778, 45.807, 12.745, 46.690]


2022-02-15 16:12:21,210 - build - river - DEBUG - Set river mask (min uparea: 30 km2) and prepare flow dirs.


2022-02-15 16:12:21,455 - build - river - DEBUG - Derive river length.


2022-02-15 16:12:27,584 - build - river - DEBUG - Derive river slope.


2022-02-15 16:12:28,277 - build - river - DEBUG - Derive rivwth from hydrography dataset.


2022-02-15 16:12:28,347 - build - landuse - INFO - Deriving N_River using average resampling (nodata=-999.0).


2022-02-15 16:12:28,361 - build - data_adapter - INFO - DataCatalog: Getting rivers_lin2019_v1 GeoDataFrame vector data from /home/runner/.hydromt_data/data/v0.0.6/rivers_lin2019_v1.gpkg
2022-02-15 16:12:28,362 - build - data_adapter - INFO - GeoDataFrame: Read vector data and clip to geom (epsg:4326) [11.778, 45.807, 12.745, 46.690].


2022-02-15 16:12:28,589 - build - river - DEBUG - Derive ['rivwth', 'qbankfull'] from shapefile.


2022-02-15 16:12:28,683 - build - river - DEBUG - Valid for 381/655 river cells (max dist: 392 m).


2022-02-15 16:12:30,359 - build - wflow - DEBUG - Adding rivers vector to staticgeoms.


2022-02-15 16:12:31,118 - build - model_api - INFO - setup_reservoirs.reservoirs_fn: hydro_reservoirs
2022-02-15 16:12:31,118 - build - model_api - INFO - setup_reservoirs.min_area: 1.0
2022-02-15 16:12:31,118 - build - model_api - INFO - setup_reservoirs.priority_jrc: True
2022-02-15 16:12:31,118 - build - wflow - INFO - Preparing reservoir maps.
2022-02-15 16:12:31,118 - build - data_adapter - INFO - DataCatalog: Getting hydro_reservoirs GeoDataFrame vector data from /home/runner/.hydromt_data/data/v0.0.6/hydro_reservoirs.gpkg
2022-02-15 16:12:31,121 - build - data_adapter - INFO - GeoDataFrame: Read vector data and clip to geom (epsg:4326) [11.775, 45.804, 12.745, 46.690].


2022-02-15 16:12:31,145 - build - data_adapter - DEBUG - GeoDataFrame: Convert units for 5 columns.
2022-02-15 16:12:31,148 - build - wflow - WARNING - No reservoirs of sufficient size found within region! Skipping reservoir procedures!
2022-02-15 16:12:31,148 - build - model_api - INFO - setup_lakes.lakes_fn: hydro_lakes
2022-02-15 16:12:31,148 - build - model_api - INFO - setup_lakes.min_area: 10.0
2022-02-15 16:12:31,148 - build - wflow - INFO - Preparing lake maps.
2022-02-15 16:12:31,148 - build - data_adapter - INFO - DataCatalog: Getting hydro_lakes GeoDataFrame vector data from /home/runner/.hydromt_data/data/v0.0.6/hydro_lakes.gpkg
2022-02-15 16:12:31,151 - build - data_adapter - INFO - GeoDataFrame: Read vector data and clip to geom (epsg:4326) [11.775, 45.804, 12.745, 46.690].
2022-02-15 16:12:31,168 - build - data_adapter - DEBUG - GeoDataFrame: Convert units for 1 columns.
2022-02-15 16:12:31,170 - build - wflow - WARNING - No lakes of sufficient size found within region! 

2022-02-15 16:12:31,195 - build - wflow - INFO - 1 glaciers of sufficient size found within region.
2022-02-15 16:12:31,207 - build - glaciers - DEBUG - Creating vector grid for calculating glacier fraction and storage per grid cell


2022-02-15 16:12:31,405 - build - glaciers - DEBUG - Setting glacierfrac and store values per glacier.


2022-02-15 16:12:33,951 - build - model_api - INFO - setup_lulcmaps.lulc_fn: globcover
2022-02-15 16:12:33,952 - build - model_api - INFO - setup_lulcmaps.lulc_mapping_fn: None
2022-02-15 16:12:33,952 - build - model_api - INFO - setup_lulcmaps.lulc_vars: ['landuse', 'Kext', 'N', 'PathFrac', 'RootingDepth', 'Sl', 'Swood', 'WaterFrac']
2022-02-15 16:12:33,952 - build - wflow - INFO - Preparing LULC parameter maps.
2022-02-15 16:12:33,952 - build - data_adapter - INFO - DataCatalog: Getting globcover RasterDataset raster data from /home/runner/.hydromt_data/data/v0.0.6/globcover.tif
2022-02-15 16:12:33,962 - build - data_adapter - DEBUG - RasterDataset: Clip with geom - [11.778, 45.807, 12.745, 46.690]


2022-02-15 16:12:33,982 - build - landuse - INFO - Deriving landuse using nearest resampling (nodata=230).
2022-02-15 16:12:34,020 - build - landuse - INFO - Deriving Kext using average resampling (nodata=-999.0).


2022-02-15 16:12:34,061 - build - landuse - INFO - Deriving N using average resampling (nodata=-999.0).


2022-02-15 16:12:34,101 - build - landuse - INFO - Deriving PathFrac using average resampling (nodata=-999.0).


2022-02-15 16:12:34,140 - build - landuse - INFO - Deriving RootingDepth using average resampling (nodata=-999).
2022-02-15 16:12:34,179 - build - landuse - INFO - Deriving Sl using average resampling (nodata=-999.0).


2022-02-15 16:12:34,218 - build - landuse - INFO - Deriving Swood using average resampling (nodata=-999.0).


2022-02-15 16:12:34,256 - build - landuse - INFO - Deriving WaterFrac using average resampling (nodata=-999).


2022-02-15 16:12:34,302 - build - model_api - INFO - setup_laimaps.lai_fn: modis_lai
2022-02-15 16:12:34,302 - build - wflow - INFO - Preparing LAI maps.
2022-02-15 16:12:34,302 - build - data_adapter - INFO - DataCatalog: Getting modis_lai RasterDataset netcdf data from /home/runner/.hydromt_data/data/v0.0.6/modis_lai.nc
2022-02-15 16:12:34,335 - build - data_adapter - DEBUG - RasterDataset: Clip with geom - [11.778, 45.807, 12.745, 46.690]


2022-02-15 16:12:34,345 - build - data_adapter - DEBUG - RasterDataset: Convert units for 1 variables.
2022-02-15 16:12:34,351 - build - landuse - INFO - Deriving LAI using average resampling (nodata=None).


2022-02-15 16:12:34,412 - build - model_api - INFO - setup_soilmaps.soil_fn: soilgrids
2022-02-15 16:12:34,412 - build - model_api - INFO - setup_soilmaps.ptf_ksatver: brakensiek
2022-02-15 16:12:34,413 - build - wflow - INFO - Preparing soil parameter maps.
2022-02-15 16:12:34,413 - build - data_adapter - INFO - DataCatalog: Getting soilgrids RasterDataset raster data from /home/runner/.hydromt_data/data/v0.0.6/soilgrids/{variable}.tif


2022-02-15 16:12:34,718 - build - data_adapter - DEBUG - RasterDataset: Clip with geom - [11.778, 45.807, 12.745, 46.690]
2022-02-15 16:12:34,738 - build - data_adapter - DEBUG - RasterDataset: Convert units for 21 variables.


2022-02-15 16:12:35,090 - build - soilgrids - INFO - calculate and resample thetaS


2022-02-15 16:12:35,230 - build - soilgrids - INFO - calculate and resample thetaR


2022-02-15 16:12:35,393 - build - soilgrids - INFO - calculate and resample KsatVer


2022-02-15 16:12:35,422 - build - soilgrids - INFO - calculate and resample pore size distribution index


2022-02-15 16:12:35,490 - build - soilgrids - INFO - fit z - log(KsatVer) with numpy linalg regression (y = b*x) -> M_


2022-02-15 16:12:36,036 - build - soilgrids - INFO - fit zi - Ksat with curve_fit (scipy.optimize) -> M


2022-02-15 16:12:39,188 - build - soilgrids - INFO - Interpolate NAN values for thetaS


2022-02-15 16:12:39,352 - build - soilgrids - INFO - Interpolate NAN values for thetaR


2022-02-15 16:12:39,369 - build - soilgrids - INFO - Interpolate NAN values for SoilThickness
2022-02-15 16:12:39,387 - build - soilgrids - INFO - Interpolate NAN values for SoilMinThickness


2022-02-15 16:12:39,617 - build - soilgrids - INFO - Interpolate NAN values for c


2022-02-15 16:12:39,676 - build - soilgrids - INFO - Interpolate NAN values for KsatVer


2022-02-15 16:12:39,734 - build - soilgrids - INFO - Interpolate NAN values for KsatVer_0.0cm


2022-02-15 16:12:39,796 - build - soilgrids - INFO - Interpolate NAN values for KsatVer_5.0cm


2022-02-15 16:12:39,858 - build - soilgrids - INFO - Interpolate NAN values for KsatVer_15.0cm


2022-02-15 16:12:39,918 - build - soilgrids - INFO - Interpolate NAN values for KsatVer_30.0cm


2022-02-15 16:12:39,977 - build - soilgrids - INFO - Interpolate NAN values for KsatVer_60.0cm


2022-02-15 16:12:40,037 - build - soilgrids - INFO - Interpolate NAN values for KsatVer_100.0cm


2022-02-15 16:12:40,094 - build - soilgrids - INFO - Interpolate NAN values for KsatVer_200.0cm


2022-02-15 16:12:40,314 - build - soilgrids - INFO - Interpolate NAN values for M_original_


2022-02-15 16:12:40,542 - build - soilgrids - INFO - Interpolate NAN values for M_


2022-02-15 16:12:40,760 - build - soilgrids - INFO - Interpolate NAN values for f_


2022-02-15 16:12:40,985 - build - soilgrids - INFO - Interpolate NAN values for M_original


2022-02-15 16:12:41,210 - build - soilgrids - INFO - Interpolate NAN values for M


2022-02-15 16:12:41,419 - build - soilgrids - INFO - Interpolate NAN values for f


2022-02-15 16:12:41,539 - build - soilgrids - INFO - Interpolate NAN values for wflow_soil


2022-02-15 16:12:41,579 - build - model_api - INFO - setup_gauges.gauges_fn: grdc
2022-02-15 16:12:41,579 - build - model_api - INFO - setup_gauges.source_gdf: None
2022-02-15 16:12:41,579 - build - model_api - INFO - setup_gauges.snap_to_river: True
2022-02-15 16:12:41,579 - build - model_api - INFO - setup_gauges.mask: None
2022-02-15 16:12:41,579 - build - model_api - INFO - setup_gauges.derive_subcatch: False
2022-02-15 16:12:41,579 - build - model_api - INFO - setup_gauges.derive_outlet: True
2022-02-15 16:12:41,579 - build - model_api - INFO - setup_gauges.basename: None
2022-02-15 16:12:41,579 - build - model_api - INFO - setup_gauges.update_toml: True
2022-02-15 16:12:41,579 - build - model_api - INFO - setup_gauges.gauge_toml_header: None
2022-02-15 16:12:41,579 - build - model_api - INFO - setup_gauges.gauge_toml_param: None
2022-02-15 16:12:41,579 - build - wflow - INFO - Gauges locations set based on river outlets.
2022-02-15 16:12:41,586 - build - wflow - INFO - Gauges map

2022-02-15 16:12:41,612 - build - data_adapter - INFO - DataCatalog: Getting era5 RasterDataset netcdf data from /home/runner/.hydromt_data/data/v0.0.6/era5.nc
2022-02-15 16:12:41,625 - build - data_adapter - DEBUG - RasterDataset: Shifting time labels with 86400 sec.
2022-02-15 16:12:41,626 - build - data_adapter - DEBUG - RasterDataset: Slicing time dim ('2010-01-01T00:00:00', '2010-03-31T00:00:00')
2022-02-15 16:12:41,635 - build - data_adapter - DEBUG - RasterDataset: Clip with geom - [11.778, 45.807, 12.745, 46.690]
2022-02-15 16:12:41,645 - build - data_adapter - DEBUG - RasterDataset: Convert units for 1 variables.


2022-02-15 16:12:41,696 - build - model_api - INFO - setup_temp_pet_forcing.temp_pet_fn: era5
2022-02-15 16:12:41,696 - build - model_api - INFO - setup_temp_pet_forcing.pet_method: debruin
2022-02-15 16:12:41,696 - build - model_api - INFO - setup_temp_pet_forcing.press_correction: True
2022-02-15 16:12:41,696 - build - model_api - INFO - setup_temp_pet_forcing.temp_correction: True
2022-02-15 16:12:41,696 - build - model_api - INFO - setup_temp_pet_forcing.dem_forcing_fn: era5_orography
2022-02-15 16:12:41,696 - build - model_api - INFO - setup_temp_pet_forcing.skip_pet: False
2022-02-15 16:12:41,696 - build - model_api - INFO - setup_temp_pet_forcing.chunksize: None
2022-02-15 16:12:41,697 - build - data_adapter - INFO - DataCatalog: Getting era5 RasterDataset netcdf data from /home/runner/.hydromt_data/data/v0.0.6/era5.nc
2022-02-15 16:12:41,706 - build - data_adapter - DEBUG - RasterDataset: Shifting time labels with 86400 sec.
2022-02-15 16:12:41,708 - build - data_adapter - DEBU

2022-02-15 16:12:41,716 - build - data_adapter - DEBUG - RasterDataset: Clip with geom - [11.778, 45.807, 12.745, 46.690]
2022-02-15 16:12:41,727 - build - data_adapter - DEBUG - RasterDataset: Convert units for 4 variables.
2022-02-15 16:12:41,757 - build - data_adapter - INFO - DataCatalog: Getting era5_orography RasterDataset netcdf data from /home/runner/.hydromt_data/data/v0.0.6/era5_orography.nc


2022-02-15 16:12:41,769 - build - data_adapter - DEBUG - RasterDataset: Clip with geom - [11.625, 45.625, 12.875, 46.875]
2022-02-15 16:12:41,780 - build - data_adapter - DEBUG - RasterDataset: Convert units for 1 variables.


2022-02-15 16:12:42,087 - build - wflow - INFO - Write model data to /home/runner/work/hydromt_wflow/hydromt_wflow/docs/examples/examples/wflow_test_full
2022-02-15 16:12:42,099 - build - model_api - INFO - Writing model config to /home/runner/work/hydromt_wflow/hydromt_wflow/docs/examples/examples/wflow_test_full/wflow_sbm.toml
2022-02-15 16:12:42,099 - build - wflow - INFO - Write staticmaps to /home/runner/work/hydromt_wflow/hydromt_wflow/docs/examples/examples/wflow_test_full/staticmaps.nc


2022-02-15 16:12:42,573 - build - wflow - INFO - Writing model staticgeom to file.


2022-02-15 16:12:42,677 - build - wflow - INFO - Write forcing file


2022-02-15 16:12:42,682 - build - wflow - INFO - Process forcing; saving to /home/runner/work/hydromt_wflow/hydromt_wflow/docs/examples/examples/wflow_test_full/inmaps-era5-2010.nc
[                                        ] | 0% Completed |  0.0s

[########################################] | 100% Completed |  0.1s


With this example we build a complete wflow model including forcing. Compared to the previous **hydromt build** we have added:
* `-i wflow_build.ini` : setup configuration file including all components to build and their arguments

Next we check which files have been created. The model root should contain two netcdf (.nc) files, one for the staticmaps and one for the forcing data, a wflow configuration (.toml) file. These files are sufficient to run the wflow model. In addition several geometry (.geojson) files are saved in the *staticgeoms* folder.  Finally, the setup process is logged in the hydromt.log file. 

In [6]:
import os

root = "wflow_test_full"
for path, _, files in os.walk(root):
    print(path)
    for name in files:
        if name.endswith(".xml"):
            continue
        print(f" - {name}")

wflow_test_full
 - inmaps-era5-2010.nc
 - hydromt.log
 - hydromt_data.yml
 - staticmaps.nc
 - wflow_sbm.toml
wflow_test_full/run_default
wflow_test_full/staticgeoms
 - region.geojson
 - basins.geojson
 - glaciers.geojson
 - rivers.geojson
 - gauges.geojson
 - gauges_grdc.geojson
wflow_test_full/instate


### Visualize and/or inspect model schematization

* The **wflow plot** example notebook contains scripts to visualize your model
* The **wflow nc to raster files** example notebook contains scripts to write the nc model files to a netcdf which can be used to inspect (and modify) the model layers in e.g. QGIS.