## Build a Wflow model from scratch

This notebook demonstrates how to prepare **Wflow** model from scratch using the command line interace (CLI).

All lines in this notebook which start with `!` are executed from the command line. Within the notebook environment the logging messages are shown after completion. You can also copy these lines and paste these in your shell to get more direct feedback.

### hydroMT CLI build interface

Lets first check if the Wflow model is recognized by hydromt

In [1]:
# this should return "wflow, wflow_seciment"
!hydromt --models

hydroMT model plugins: wflow (v0.1.2), wflow_sediment (v0.1.2)


Using the **hydromt build** API we can setup a complete model from scratch. Let's get an overview of all the available options:

In [2]:
!hydromt build --help

Usage: hydromt build [OPTIONS] MODEL MODEL_ROOT REGION

  Build models from source data.

  Example usage:
  --------------

  To build a wflow model for a subbasin using and point coordinates snapped to cells with stream order >= 4
  hydromt build wflow /path/to/model_root "{'subbasin': [-7.24, 62.09], 'strord': 4}" -i /path/to/wflow_config.ini

  To build a wflow model based on basin ID
  hydromt build wflow /path/to/model_root "{'basin': 230001006}"

  To build a sfincs model based on a bbox (for Texel)
  hydromt build sfincs /path/to/model_root "{'bbox': [4.6891,52.9750,4.9576,53.1994]}"

Options:
  -r, --res FLOAT             Model resolution in model src.
  --build-base / --build-all  Deprecated!
  --opt TEXT                  Component specific keyword arguments, see the
                              setup_<component> method of the specific model
                              for more information about the arguments.

  -i, --config PATH           Path to hydroMT configuration fi

### setup wflow model base layers 

In [3]:
# NOTE: copy this line (without !) to your shell for more direct feedback
!hydromt build wflow "./wflow_test_base" "{'subbasin': [12.2051, 45.8331], 'strord': 4, 'bounds': [11.70, 45.35, 12.95, 46.70]}" -r 0.00833 -v

2021-09-01 15:27:11,466 - build - log - INFO - HydroMT version: 0.4.3.dev
2021-09-01 15:27:11,466 - build - main - INFO - Building instance of wflow model at /home/runner/work/hydromt_wflow/hydromt_wflow/docs/examples/examples/wflow_test_base.
2021-09-01 15:27:11,466 - build - main - INFO - User settings:
2021-09-01 15:27:11,506 - build - model_api - INFO - Initializing wflow model from hydromt_wflow (v0.1.2).
2021-09-01 15:27:11,507 - build - model_api - INFO - setup_basemaps.region: {'subbasin': [12.2051, 45.8331], 'strord': 4, 'bounds': [11.7, 45.35, 12.95, 46.7]}
2021-09-01 15:27:11,507 - build - model_api - INFO - setup_basemaps.res: 0.00833
2021-09-01 15:27:11,507 - build - model_api - INFO - setup_basemaps.hydrography_fn: merit_hydro
2021-09-01 15:27:11,507 - build - model_api - INFO - setup_basemaps.basin_index_fn: merit_hydro_index
2021-09-01 15:27:11,507 - build - model_api - INFO - setup_basemaps.upscale_method: ihu
2021-09-01 15:27:11,507 - build - wflow - INFO - Preparing 

2021-09-01 15:27:14,502 - build - data_adapter - INFO - Updating data sources from yml file /home/runner/.hydromt_data/data/v0.0.4/data_catalog.yml


2021-09-01 15:27:14,583 - build - data_adapter - INFO - DataCatalog: Getting merit_hydro RasterDataset raster data from /home/runner/.hydromt_data/data/v0.0.4/merit_hydro/{variable}.tif


2021-09-01 15:27:18,386 - build - basin_mask - INFO - basin bbox: [11.7750, 45.8042, 12.7450, 46.6900] / size: 664756


2021-09-01 15:27:18,697 - build - basemaps - INFO - Upscale flow direction data: 10x, ihu method.


2021-09-01 15:27:37,596 - build - wflow - INFO - Write model data to /home/runner/work/hydromt_wflow/hydromt_wflow/docs/examples/examples/wflow_test_base
2021-09-01 15:27:37,599 - build - model_api - INFO - Writing model config to /home/runner/work/hydromt_wflow/hydromt_wflow/docs/examples/examples/wflow_test_base/wflow_sbm.toml
2021-09-01 15:27:37,600 - build - wflow - INFO - Write staticmaps to /home/runner/work/hydromt_wflow/hydromt_wflow/docs/examples/examples/wflow_test_base/staticmaps.nc


2021-09-01 15:27:37,744 - build - wflow - INFO - Writing model staticgeom to file.


The example above means the following: run **hydromt build** with:

* `wflow` : i.e. build a wflow model
* `./wflow_test_base` : output model folder
* `"{'subbasin': [12.2051, 45.8331], 'strord': 4, 'bounds': [11.70, 45.35, 12.95, 46.70]}"` : derive a subbasin with its outlet at the given x,y coordinates and within the given bounds [xmin, ymin, xmax, ymax] (WGS84) snapped to a river with minimum stream order (strord) of 4. All *REGION* options are described in the [docs](https://deltares.github.io/hydromt/latest/user_guide/cli.html#region-options)
* `-r 0.0083333` : build the model at a 30 arc sec (~1km) resolution
* `-vv` : give some extra verbosity (2 * v) to display feedback on screen. Now debug messages are provided.

NOTE: As we did not specify a model configuration, only the base maps (topography and hydrography) have been setup using default parameters. To build a complete model we need the use a configuraton ini-file.

### Model setup configuration

The ini-file contains the model setup configuration and determines which components are build and in which order and optionally sets non-default arguments for each component. This configuration is passed to hydromt using `-i <path_to_ini_file>`. We have prepared several example ini-files which are available in the model repository [examples folder](https://github.com/Deltares/hydromt_wflow/tree/main/examples) and from the [docs(build_configuration)](https://deltares.github.io/hydromt_wflow/latest/user_guide/wflow/build_configuration.html). 

Each header as shown between `[...]` (e.g. `[setup_basemaps]`) corresponds to a model component. All model components are explained in the [docs(model_components)](https://deltares.github.io/hydromt_wflow/latest/user_guide/wflow/components.html). 

We will load the default wflow build ini file for inspection:

In [4]:
fn_ini = 'wflow_build.ini'
with open(fn_ini, 'r') as f:
    txt = f.read()
print(txt)

[global]
data_libs       = []            # add optional paths to data yml files

[setup_config]                  # options parsed to wflow ini file <section>.<option>
starttime = 2010-01-01T00:00:00
endtime = 2010-03-31T00:00:00
timestepsecs = 86400
input.path_forcing = inmaps-era5-2010.nc

[setup_basemaps]
hydrography_fn     = merit_hydro   # source hydrography data {merit_hydro, merit_hydro_1k}
basin_index_fn  = merit_hydro_index # source of basin index corresponding to hydrography_fn
upscale_method  = ihu           # upscaling method for flow direction data, by default 'ihu'

[setup_rivers]
hydrography_fn  = merit_hydro   # source hydrography data, should match basemaps source
river_upa       = 30            # minimum upstream area threshold for the river map [km2]
slope_len       = 2000          # length over which tp calculate river slope [m]

[setup_reservoirs]
reservoirs_fn   = hydro_reservoirs  # source for reservoirs based on GRAND: {hydro_reservoirs}; None to skip
min_area   

### Data for model setup

The `<...>_fn` arguments correspond to a data source from the `DataCatalog` which is based on a yml-file with references to the data paths/urls and how the data should be read. This file can be provided to hydromt using `-d <path_to_yml_file>`. 

By default some example data for the Piave basin will be downloaded to `~/.hydromt_data/` which is also used for this example. An overview of the available example data is provided [here](https://deltares.github.io/hydromt/latest/user_guide/data.html#available-global-datasets)
This example data is a based on the data which available from the Deltares p-drive. 
If you have acces to this drive, a pre-configured catalog file can be loaded using the `--dd` flag. 

More background how to write a data catalog yml file can be found in the [hydromt core docs](https://deltares.github.io/hydromt/latest/user_guide/data.html) 

### Setup complete wflow model 

In [5]:
# NOTE: copy this line (without !) to your shell for more direct feedback
!hydromt build wflow "./wflow_test_full" "{'subbasin': [12.2051, 45.8331], 'strord': 4, 'bounds': [11.70, 45.35, 12.95, 46.70]}" -r 0.00833 -i wflow_build.ini -vv

2021-09-01 15:27:40,867 - build - log - DEBUG - Writing log messages to new file /home/runner/work/hydromt_wflow/hydromt_wflow/docs/examples/examples/wflow_test_full/hydromt.log.
2021-09-01 15:27:40,868 - build - log - INFO - HydroMT version: 0.4.3.dev
2021-09-01 15:27:40,868 - build - main - INFO - Building instance of wflow model at /home/runner/work/hydromt_wflow/hydromt_wflow/docs/examples/examples/wflow_test_full.
2021-09-01 15:27:40,868 - build - main - INFO - User settings:


2021-09-01 15:27:40,912 - build - model_plugins - DEBUG - Loaded model plugin 'wflow = hydromt_wflow.wflow.WflowModel' (0.1.2)
2021-09-01 15:27:40,912 - build - model_api - INFO - Initializing wflow model from hydromt_wflow (v0.1.2).
2021-09-01 15:27:40,912 - build - model_api - DEBUG - Setting model config options.
2021-09-01 15:27:40,916 - build - model_api - DEBUG - Default config read from /usr/share/miniconda/envs/hydromt-wflow/lib/python3.9/site-packages/hydromt_wflow/data/wflow/wflow_sbm.toml
2021-09-01 15:27:40,916 - build - model_api - INFO - setup_basemaps.region: {'subbasin': [12.2051, 45.8331], 'strord': 4, 'bounds': [11.7, 45.35, 12.95, 46.7]}
2021-09-01 15:27:40,916 - build - model_api - INFO - setup_basemaps.res: 0.00833
2021-09-01 15:27:40,916 - build - model_api - INFO - setup_basemaps.hydrography_fn: merit_hydro
2021-09-01 15:27:40,916 - build - model_api - INFO - setup_basemaps.basin_index_fn: merit_hydro_index
2021-09-01 15:27:40,916 - build - model_api - INFO - set

2021-09-01 15:27:40,997 - build - data_adapter - INFO - DataCatalog: Getting merit_hydro RasterDataset raster data from /home/runner/.hydromt_data/data/v0.0.4/merit_hydro/{variable}.tif


2021-09-01 15:27:41,087 - build - basin_mask - DEBUG - Parsed region (kind=subbasin): {'strord': 4, 'bounds': [11.7, 45.35, 12.95, 46.7], 'xy': [12.2051, 45.8331]}


2021-09-01 15:27:44,753 - build - basin_mask - INFO - basin bbox: [11.7750, 45.8042, 12.7450, 46.6900] / size: 664756


2021-09-01 15:27:44,872 - build - wflow - DEBUG - Adding basins vector to staticgeoms.
2021-09-01 15:27:44,872 - build - basemaps - DEBUG - Mask in dataset assumed to represent subbasins.
2021-09-01 15:27:44,874 - build - basemaps - DEBUG - (Sub)basin at original resolution has 664756 cells.


2021-09-01 15:27:45,043 - build - basemaps - DEBUG - Burn subbasin outlet in upstream area data.
2021-09-01 15:27:45,061 - build - basemaps - INFO - Upscale flow direction data: 10x, ihu method.


2021-09-01 15:28:03,705 - build - basemaps - DEBUG - Derive stream order.


2021-09-01 15:28:03,919 - build - basemaps - DEBUG - Map shape: (106, 116); active cells: 6637.
2021-09-01 15:28:03,920 - build - basemaps - DEBUG - Outlet coordinates (1/1): (12.20750,45.83583).


2021-09-01 15:28:03,993 - build - wflow - DEBUG - Adding region vector to staticgeoms.


2021-09-01 15:28:04,006 - build - model_api - INFO - setup_rivers.hydrography_fn: merit_hydro
2021-09-01 15:28:04,006 - build - model_api - INFO - setup_rivers.river_upa: 30
2021-09-01 15:28:04,006 - build - model_api - INFO - setup_rivers.slope_len: 2000
2021-09-01 15:28:04,006 - build - model_api - INFO - setup_rivers.n_river_mapping: None
2021-09-01 15:28:04,006 - build - model_api - INFO - setup_rivers.min_rivlen_ratio: 0.1
2021-09-01 15:28:04,006 - build - wflow - INFO - Preparing river maps.
2021-09-01 15:28:04,007 - build - data_adapter - INFO - DataCatalog: Getting merit_hydro RasterDataset raster data from /home/runner/.hydromt_data/data/v0.0.4/merit_hydro/{variable}.tif


2021-09-01 15:28:04,084 - build - data_adapter - DEBUG - RasterDataset: Clip with geom - [11.778, 45.807, 12.745, 46.690]


2021-09-01 15:28:04,117 - build - river - DEBUG - Set river mask with upstream area threshold: 30 km2.
2021-09-01 15:28:04,126 - build - river - DEBUG - Derive river length.


2021-09-01 15:28:09,961 - build - river - DEBUG - Derive river slope.


2021-09-01 15:28:10,419 - build - landuse - INFO - Deriving N_River using average resampling (nodata=-999.0).
2021-09-01 15:28:10,433 - build - wflow - DEBUG - Adding rivers vector to staticgeoms.


2021-09-01 15:28:11,136 - build - model_api - INFO - setup_reservoirs.reservoirs_fn: hydro_reservoirs
2021-09-01 15:28:11,137 - build - model_api - INFO - setup_reservoirs.min_area: 1.0
2021-09-01 15:28:11,137 - build - model_api - INFO - setup_reservoirs.priority_jrc: True
2021-09-01 15:28:11,137 - build - wflow - INFO - Preparing reservoir maps.
2021-09-01 15:28:11,137 - build - data_adapter - INFO - DataCatalog: Getting hydro_reservoirs GeoDataFrame vector data from /home/runner/.hydromt_data/data/v0.0.4/hydro_reservoirs.gpkg
2021-09-01 15:28:11,142 - build - data_adapter - INFO - GeoDataFrame: Read vector data and clip to geom (epsg:4326) [11.775, 45.804, 12.745, 46.690].


2021-09-01 15:28:11,192 - build - data_adapter - DEBUG - GeoDataFrame: Convert units for 5 columns.
2021-09-01 15:28:11,197 - build - wflow - WARNING - No reservoirs of sufficient size found within region! Skipping reservoir procedures!
2021-09-01 15:28:11,197 - build - model_api - INFO - setup_lakes.lakes_fn: hydro_lakes
2021-09-01 15:28:11,197 - build - model_api - INFO - setup_lakes.min_area: 10.0
2021-09-01 15:28:11,197 - build - wflow - INFO - Preparing lake maps.
2021-09-01 15:28:11,197 - build - data_adapter - INFO - DataCatalog: Getting hydro_lakes GeoDataFrame vector data from /home/runner/.hydromt_data/data/v0.0.4/hydro_lakes.gpkg
2021-09-01 15:28:11,202 - build - data_adapter - INFO - GeoDataFrame: Read vector data and clip to geom (epsg:4326) [11.775, 45.804, 12.745, 46.690].


2021-09-01 15:28:11,240 - build - data_adapter - DEBUG - GeoDataFrame: Convert units for 1 columns.
2021-09-01 15:28:11,242 - build - wflow - WARNING - No lakes of sufficient size found within region! Skipping lake procedures!
2021-09-01 15:28:11,243 - build - model_api - INFO - setup_glaciers.glaciers_fn: rgi
2021-09-01 15:28:11,243 - build - model_api - INFO - setup_glaciers.min_area: 1.0
2021-09-01 15:28:11,243 - build - wflow - INFO - Preparing glacier maps.
2021-09-01 15:28:11,243 - build - data_adapter - INFO - DataCatalog: Getting rgi GeoDataFrame vector data from /home/runner/.hydromt_data/data/v0.0.4/rgi.gpkg
2021-09-01 15:28:11,248 - build - data_adapter - INFO - GeoDataFrame: Read vector data and clip to geom (epsg:4326) [11.775, 45.804, 12.745, 46.690].


2021-09-01 15:28:11,296 - build - wflow - INFO - 1 glaciers of sufficient size found within region.


2021-09-01 15:28:11,320 - build - glaciers - DEBUG - Creating vector grid for calculating glacier fraction and storage per grid cell


2021-09-01 15:28:11,583 - build - glaciers - DEBUG - Setting glacierfrac and store values per glacier.


2021-09-01 15:28:13,371 - build - model_api - INFO - setup_riverwidth.predictor: discharge
2021-09-01 15:28:13,371 - build - model_api - INFO - setup_riverwidth.fill: False
2021-09-01 15:28:13,372 - build - model_api - INFO - setup_riverwidth.fit: False
2021-09-01 15:28:13,372 - build - model_api - INFO - setup_riverwidth.min_wth: 1
2021-09-01 15:28:13,372 - build - model_api - INFO - setup_riverwidth.precip_fn: chelsa
2021-09-01 15:28:13,372 - build - model_api - INFO - setup_riverwidth.climate_fn: koppen_geiger
2021-09-01 15:28:13,372 - build - data_adapter - INFO - DataCatalog: Getting chelsa RasterDataset raster data from /home/runner/.hydromt_data/data/v0.0.4/chelsa.tif
2021-09-01 15:28:13,390 - build - data_adapter - DEBUG - RasterDataset: Clip with geom - [11.778, 45.807, 12.745, 46.690]


2021-09-01 15:28:13,417 - build - data_adapter - INFO - DataCatalog: Getting koppen_geiger RasterDataset raster data from /home/runner/.hydromt_data/data/v0.0.4/koppen_geiger.tif
2021-09-01 15:28:13,433 - build - data_adapter - DEBUG - RasterDataset: Clip with geom - [11.778, 45.807, 12.745, 46.690]


2021-09-01 15:28:13,461 - build - river - DEBUG - Deriving predictor "discharge" values
2021-09-01 15:28:13,469 - build - river - DEBUG - Basin base climate classification: 3 (Cfb)


2021-09-01 15:28:13,522 - build - river - WARNING - mask variable "lakeareas" not found in maps.
2021-09-01 15:28:13,522 - build - river - WARNING - mask variable "resareas" not found in maps.
2021-09-01 15:28:13,522 - build - river - DEBUG - glacareas masked out in rivwth data.
2021-09-01 15:28:13,523 - build - river - INFO - Using "width = a*discharge^b"; where a=6.33, b=0.55 (nse=-0.447; outliers=6.09%)
2021-09-01 15:28:13,523 - build - river - INFO - rivwth set globally based on width-discharge relationship.
2021-09-01 15:28:13,525 - build - model_api - INFO - setup_lulcmaps.lulc_fn: globcover
2021-09-01 15:28:13,526 - build - model_api - INFO - setup_lulcmaps.lulc_mapping_fn: None
2021-09-01 15:28:13,526 - build - model_api - INFO - setup_lulcmaps.lulc_vars: ['landuse', 'Kext', 'N', 'PathFrac', 'RootingDepth', 'Sl', 'Swood', 'WaterFrac']
2021-09-01 15:28:13,526 - build - wflow - INFO - Preparing LULC parameter maps.
2021-09-01 15:28:13,526 - build - data_adapter - INFO - DataCatal

2021-09-01 15:28:13,582 - build - landuse - INFO - Deriving landuse using nearest resampling (nodata=230).


2021-09-01 15:28:13,635 - build - landuse - INFO - Deriving Kext using average resampling (nodata=-999.0).


2021-09-01 15:28:13,686 - build - landuse - INFO - Deriving N using average resampling (nodata=-999.0).


2021-09-01 15:28:13,738 - build - landuse - INFO - Deriving PathFrac using average resampling (nodata=-999.0).


2021-09-01 15:28:13,789 - build - landuse - INFO - Deriving RootingDepth using average resampling (nodata=-999).


2021-09-01 15:28:13,841 - build - landuse - INFO - Deriving Sl using average resampling (nodata=-999.0).


2021-09-01 15:28:13,893 - build - landuse - INFO - Deriving Swood using average resampling (nodata=-999.0).


2021-09-01 15:28:13,944 - build - landuse - INFO - Deriving WaterFrac using average resampling (nodata=-999).


2021-09-01 15:28:14,006 - build - model_api - INFO - setup_laimaps.lai_fn: modis_lai
2021-09-01 15:28:14,006 - build - wflow - INFO - Preparing LAI maps.
2021-09-01 15:28:14,006 - build - data_adapter - INFO - DataCatalog: Getting modis_lai RasterDataset netcdf data from /home/runner/.hydromt_data/data/v0.0.4/modis_lai.nc


2021-09-01 15:28:14,027 - build - data_adapter - DEBUG - RasterDataset: Clip with geom - [11.778, 45.807, 12.745, 46.690]
2021-09-01 15:28:14,055 - build - data_adapter - DEBUG - RasterDataset: Convert units for 1 variables.


2021-09-01 15:28:14,062 - build - landuse - INFO - Deriving LAI using average resampling (nodata=None).


2021-09-01 15:28:14,139 - build - model_api - INFO - setup_soilmaps.soil_fn: soilgrids
2021-09-01 15:28:14,139 - build - model_api - INFO - setup_soilmaps.ptf_ksatver: brakensiek
2021-09-01 15:28:14,139 - build - wflow - INFO - Preparing soil parameter maps.
2021-09-01 15:28:14,140 - build - data_adapter - INFO - DataCatalog: Getting soilgrids RasterDataset raster data from /home/runner/.hydromt_data/data/v0.0.4/soilgrids/{variable}.tif


2021-09-01 15:28:14,521 - build - data_adapter - DEBUG - RasterDataset: Clip with geom - [11.778, 45.807, 12.745, 46.690]
2021-09-01 15:28:14,561 - build - data_adapter - DEBUG - RasterDataset: Convert units for 21 variables.


2021-09-01 15:28:15,016 - build - soilgrids - INFO - calculate and resample thetaS


2021-09-01 15:28:15,673 - build - soilgrids - INFO - calculate and resample thetaR


2021-09-01 15:28:16,572 - build - soilgrids - INFO - calculate and resample KsatVer


2021-09-01 15:28:18,789 - build - soilgrids - INFO - calculate and resample pore size distribution index


2021-09-01 15:28:20,946 - build - soilgrids - INFO - fit z - log(KsatVer) with numpy linalg regression (y = b*x) -> M_


2021-09-01 15:28:21,354 - build - soilgrids - INFO - fit zi - Ksat with curve_fit (scipy.optimize) -> M


2021-09-01 15:28:25,536 - build - model_api - INFO - setup_gauges.gauges_fn: grdc
2021-09-01 15:28:25,536 - build - model_api - INFO - setup_gauges.source_gdf: None
2021-09-01 15:28:25,536 - build - model_api - INFO - setup_gauges.snap_to_river: True
2021-09-01 15:28:25,536 - build - model_api - INFO - setup_gauges.mask: None
2021-09-01 15:28:25,536 - build - model_api - INFO - setup_gauges.derive_subcatch: False
2021-09-01 15:28:25,536 - build - model_api - INFO - setup_gauges.derive_outlet: True
2021-09-01 15:28:25,536 - build - model_api - INFO - setup_gauges.basename: None
2021-09-01 15:28:25,536 - build - model_api - INFO - setup_gauges.update_toml: True
2021-09-01 15:28:25,536 - build - model_api - INFO - setup_gauges.gauge_toml_header: None
2021-09-01 15:28:25,537 - build - model_api - INFO - setup_gauges.gauge_toml_param: None
2021-09-01 15:28:25,537 - build - wflow - INFO - Gauges locations set based on river outlets.


2021-09-01 15:28:25,553 - build - wflow - INFO - Gauges map based on catchment river outlets added.
2021-09-01 15:28:25,553 - build - data_adapter - INFO - DataCatalog: Getting grdc GeoDataFrame csv data from /home/runner/.hydromt_data/data/v0.0.4/grdc.csv
2021-09-01 15:28:25,558 - build - data_adapter - INFO - GeoDataFrame: Read csv data and clip to geom (epsg:4326) [11.775, 45.804, 12.745, 46.690].
2021-09-01 15:28:25,585 - build - wflow - INFO - 3 grdc gauge locations found within domain


2021-09-01 15:28:25,601 - build - wflow - INFO - Gauges map from grdc added.
2021-09-01 15:28:25,602 - build - model_api - INFO - setup_precip_forcing.precip_fn: era5
2021-09-01 15:28:25,602 - build - model_api - INFO - setup_precip_forcing.precip_clim_fn: None
2021-09-01 15:28:25,602 - build - model_api - INFO - setup_precip_forcing.chunksize: None
2021-09-01 15:28:25,602 - build - data_adapter - INFO - DataCatalog: Getting era5 RasterDataset netcdf data from /home/runner/.hydromt_data/data/v0.0.4/era5.nc
2021-09-01 15:28:25,617 - build - data_adapter - DEBUG - RasterDataset: Shifting time labels with 86400 sec.
2021-09-01 15:28:25,619 - build - data_adapter - DEBUG - RasterDataset: Slicing time dim ('2010-01-01T00:00:00', '2010-03-31T00:00:00')
2021-09-01 15:28:25,635 - build - data_adapter - DEBUG - RasterDataset: Clip with geom - [11.778, 45.807, 12.745, 46.690]


2021-09-01 15:28:25,662 - build - data_adapter - DEBUG - RasterDataset: Convert units for 1 variables.


2021-09-01 15:28:25,755 - build - model_api - INFO - setup_temp_pet_forcing.temp_pet_fn: era5
2021-09-01 15:28:25,755 - build - model_api - INFO - setup_temp_pet_forcing.pet_method: debruin
2021-09-01 15:28:25,755 - build - model_api - INFO - setup_temp_pet_forcing.press_correction: True
2021-09-01 15:28:25,755 - build - model_api - INFO - setup_temp_pet_forcing.temp_correction: True
2021-09-01 15:28:25,755 - build - model_api - INFO - setup_temp_pet_forcing.dem_forcing_fn: era5_orography
2021-09-01 15:28:25,756 - build - model_api - INFO - setup_temp_pet_forcing.skip_pet: False
2021-09-01 15:28:25,756 - build - model_api - INFO - setup_temp_pet_forcing.chunksize: None
2021-09-01 15:28:25,756 - build - data_adapter - INFO - DataCatalog: Getting era5 RasterDataset netcdf data from /home/runner/.hydromt_data/data/v0.0.4/era5.nc
2021-09-01 15:28:25,766 - build - data_adapter - DEBUG - RasterDataset: Shifting time labels with 86400 sec.
2021-09-01 15:28:25,768 - build - data_adapter - DEBU

2021-09-01 15:28:25,809 - build - data_adapter - DEBUG - RasterDataset: Convert units for 4 variables.
2021-09-01 15:28:25,849 - build - data_adapter - INFO - DataCatalog: Getting era5_orography RasterDataset netcdf data from /home/runner/.hydromt_data/data/v0.0.4/era5_orography.nc


2021-09-01 15:28:25,868 - build - data_adapter - DEBUG - RasterDataset: Clip with geom - [11.625, 45.625, 12.875, 46.875]
2021-09-01 15:28:25,895 - build - data_adapter - DEBUG - RasterDataset: Convert units for 1 variables.


2021-09-01 15:28:26,370 - build - wflow - INFO - Write model data to /home/runner/work/hydromt_wflow/hydromt_wflow/docs/examples/examples/wflow_test_full
2021-09-01 15:28:26,370 - build - model_api - INFO - Writing model config to /home/runner/work/hydromt_wflow/hydromt_wflow/docs/examples/examples/wflow_test_full/wflow_sbm.toml
2021-09-01 15:28:26,371 - build - wflow - INFO - Write staticmaps to /home/runner/work/hydromt_wflow/hydromt_wflow/docs/examples/examples/wflow_test_full/staticmaps.nc


2021-09-01 15:28:26,874 - build - wflow - INFO - Writing model staticgeom to file.


2021-09-01 15:28:27,056 - build - wflow - INFO - Write forcing file
2021-09-01 15:28:27,063 - build - wflow - INFO - Process forcing; saving to /home/runner/work/hydromt_wflow/hydromt_wflow/docs/examples/examples/wflow_test_full/inmaps-era5-2010.nc


[                                        ] | 0% Completed |  0.0s

[########################################] | 100% Completed |  0.1s


With this example we build a complete wflow model including forcing. Compared to the previous **hydromt build** we have added:
* `-i wflow_build.ini` : setup configuration file including all components to build and their arguments

Next we check which files have been created. The model root should contain two netcdf (.nc) files, one for the staticmaps and one for the forcing data, a wflow configuration (.toml) file. These files are sufficient to run the wflow model. In addition several geometry (.geojson) files are saved in the *staticgeoms* folder.  Finally, the setup process is logged in the hydromt.log file. 

In [6]:
import os
root = 'wflow_test_full'
for path, _, files in os.walk(root):
    print(path)
    for name in files:
        if name.endswith('.xml'):
            continue
        print(f' - {name}')

wflow_test_full
 - wflow_sbm.toml
 - hydromt.log
 - staticmaps.nc
 - inmaps-era5-2010.nc
wflow_test_full/run_default
wflow_test_full/staticgeoms
 - glaciers.geojson
 - gauges.geojson
 - basins.geojson
 - gauges_grdc.geojson
 - rivers.geojson
 - region.geojson
wflow_test_full/instate


### Visualize and/or inspect model schematization

* The **wflow plot** example notebook contains scripts to visualize your model
* The **wflow nc to raster files** example notebook contains scripts to write the nc model files to a netcdf which can be used to inspect (and modify) the model layers in e.g. QGIS.