## Build a Wflow sediment model

This notebook demonstrates how to prepare a **Wflow sediment** model using the command line interace (CLI).

All lines in this notebook which start with `!` are executed from the command line. Within the notebook environment the logging messages are shown after completion. You can also copy these lines and paste these in your shell to get more direct feedback.

### hydroMT CLI build interface

Lets first check if the Wflow sediment model is recognized by hydromt

In [1]:
# this should return "wflow, wflow_sediment"
!hydromt --models

hydroMT model plugins: wflow (v0.1.2), wflow_sediment (v0.1.2)


Using the **hydromt build** API we can setup a complete model from scratch. Let's get an overview of all the available options:

In [2]:
!hydromt build --help

Usage: hydromt build [OPTIONS] MODEL MODEL_ROOT REGION

  Build models from source data.

  Example usage:
  --------------

  To build a wflow model for a subbasin using and point coordinates snapped to cells with stream order >= 4
  hydromt build wflow /path/to/model_root "{'subbasin': [-7.24, 62.09], 'strord': 4}" -i /path/to/wflow_config.ini

  To build a wflow model based on basin ID
  hydromt build wflow /path/to/model_root "{'basin': 230001006}"

  To build a sfincs model based on a bbox (for Texel)
  hydromt build sfincs /path/to/model_root "{'bbox': [4.6891,52.9750,4.9576,53.1994]}"

Options:
  -r, --res FLOAT             Model resolution in model src.
  --build-base / --build-all  Deprecated!
  --opt TEXT                  Component specific keyword arguments, see the
                              setup_<component> method of the specific model
                              for more information about the arguments.

  -i, --config PATH           Path to hydroMT configuration fi

### Model setup configuration

The ini-file contains the model setup configuration and determines which components are build and in which order and optionally sets non-default arguments for each component. This configuration is passed to hydromt using `-i <path_to_ini_file>`. We have prepared several example ini-files which are available in the model repository [examples folder](https://github.com/Deltares/hydromt_wflow/tree/main/examples) and from the [docs(build_configuration)](https://deltares.github.io/hydromt_wflow/latest/user_guide/wflow/build_configuration.html). 

Each header as shown between `[...]` (e.g. `[setup_basemaps]`) corresponds to a model component. All model components are explained in the [docs(model_components)](https://deltares.github.io/hydromt_wflow/latest/user_guide/wflow/components.html). 

We will load the default wflow sediment build ini file for inspection:

In [3]:
fn_ini = 'wflow_sediment_build.ini'
with open(fn_ini, 'r') as f:
    txt = f.read()
print(txt)

[global]
data_libs        = []               # add optional paths to data yml files

[setup_config]                      # options parsed to wflow ini file <section>.<option>
starttime = 2010-01-01T00:00:00
endtime = 2010-03-31T00:00:00
timestepsecs = 86400

[setup_basemaps]
hydrography_fn   = merit_hydro      # source hydrography data {merit_hydro, merit_hydro_1k}
basin_index_fn   = merit_hydro_index # source of basin index corresponding to hydrography_fn
upscale_method   = ihu              # upscaling method for flow direction data, by default 'ihu'

[setup_rivers]
hydrography_fn   = merit_hydro   # source hydrography data {merit_hydro, merit_hydro_1k}
river_upa        = 30               # minimum upstream area threshold for the river map [km2]
slope_len        = 2000             # length over which tp calculate river slope [m]

[setup_reservoirs]
reservoirs_fn    = hydro_reservoirs # source for reservoirs based on GRAND: {hydro_reservoirs}; None to skip
min_area         = 1.0       

### Setup wflow sediment model from scratch

In [4]:
# NOTE: copy this line (without !) to your shell for more direct feedback
!hydromt build wflow_sediment "./wflow_test_sediment" "{'subbasin': [12.2051, 45.8331], 'strord': 4, 'bounds': [11.70, 45.35, 12.95, 46.70]}" -r 0.00833 -i wflow_sediment_build.ini -vv

2021-09-01 15:28:38,350 - build - log - DEBUG - Writing log messages to new file /home/runner/work/hydromt_wflow/hydromt_wflow/docs/examples/examples/wflow_test_sediment/hydromt.log.
2021-09-01 15:28:38,351 - build - log - INFO - HydroMT version: 0.4.3.dev
2021-09-01 15:28:38,351 - build - main - INFO - Building instance of wflow_sediment model at /home/runner/work/hydromt_wflow/hydromt_wflow/docs/examples/examples/wflow_test_sediment.
2021-09-01 15:28:38,351 - build - main - INFO - User settings:


2021-09-01 15:28:38,394 - build - model_plugins - DEBUG - Loaded model plugin 'wflow_sediment = hydromt_wflow.wflow_sediment.WflowSedimentModel' (0.1.2)
2021-09-01 15:28:38,394 - build - model_api - INFO - Initializing wflow_sediment model from hydromt_wflow (v0.1.2).
2021-09-01 15:28:38,395 - build - model_api - DEBUG - Setting model config options.
2021-09-01 15:28:38,397 - build - model_api - DEBUG - Default config read from /usr/share/miniconda/envs/hydromt-wflow/lib/python3.9/site-packages/hydromt_wflow/data/wflow_sediment/wflow_sediment.toml
2021-09-01 15:28:38,397 - build - model_api - INFO - setup_basemaps.region: {'subbasin': [12.2051, 45.8331], 'strord': 4, 'bounds': [11.7, 45.35, 12.95, 46.7]}
2021-09-01 15:28:38,398 - build - model_api - INFO - setup_basemaps.res: 0.00833
2021-09-01 15:28:38,398 - build - model_api - INFO - setup_basemaps.hydrography_fn: merit_hydro
2021-09-01 15:28:38,398 - build - model_api - INFO - setup_basemaps.basin_index_fn: merit_hydro_index
2021-09

2021-09-01 15:28:38,481 - build - data_adapter - INFO - DataCatalog: Getting merit_hydro RasterDataset raster data from /home/runner/.hydromt_data/data/v0.0.4/merit_hydro/{variable}.tif


2021-09-01 15:28:38,570 - build - basin_mask - DEBUG - Parsed region (kind=subbasin): {'strord': 4, 'bounds': [11.7, 45.35, 12.95, 46.7], 'xy': [12.2051, 45.8331]}


2021-09-01 15:28:42,295 - build - basin_mask - INFO - basin bbox: [11.7750, 45.8042, 12.7450, 46.6900] / size: 664756


2021-09-01 15:28:42,416 - build - wflow - DEBUG - Adding basins vector to staticgeoms.
2021-09-01 15:28:42,416 - build - basemaps - DEBUG - Mask in dataset assumed to represent subbasins.
2021-09-01 15:28:42,418 - build - basemaps - DEBUG - (Sub)basin at original resolution has 664756 cells.


2021-09-01 15:28:42,587 - build - basemaps - DEBUG - Burn subbasin outlet in upstream area data.


2021-09-01 15:28:42,605 - build - basemaps - INFO - Upscale flow direction data: 10x, ihu method.


2021-09-01 15:29:01,325 - build - basemaps - DEBUG - Derive stream order.


2021-09-01 15:29:01,543 - build - basemaps - DEBUG - Map shape: (106, 116); active cells: 6637.
2021-09-01 15:29:01,543 - build - basemaps - DEBUG - Outlet coordinates (1/1): (12.20750,45.83583).


2021-09-01 15:29:01,618 - build - wflow - DEBUG - Adding region vector to staticgeoms.


2021-09-01 15:29:01,631 - build - model_api - INFO - setup_rivers.hydrography_fn: merit_hydro
2021-09-01 15:29:01,631 - build - model_api - INFO - setup_rivers.river_upa: 30
2021-09-01 15:29:01,631 - build - model_api - INFO - setup_rivers.slope_len: 2000
2021-09-01 15:29:01,632 - build - model_api - INFO - setup_rivers.n_river_mapping: None
2021-09-01 15:29:01,632 - build - model_api - INFO - setup_rivers.min_rivlen_ratio: 0.1
2021-09-01 15:29:01,632 - build - wflow - INFO - Preparing river maps.
2021-09-01 15:29:01,632 - build - data_adapter - INFO - DataCatalog: Getting merit_hydro RasterDataset raster data from /home/runner/.hydromt_data/data/v0.0.4/merit_hydro/{variable}.tif


2021-09-01 15:29:01,709 - build - data_adapter - DEBUG - RasterDataset: Clip with geom - [11.778, 45.807, 12.745, 46.690]


2021-09-01 15:29:01,742 - build - river - DEBUG - Set river mask with upstream area threshold: 30 km2.
2021-09-01 15:29:01,752 - build - river - DEBUG - Derive river length.


2021-09-01 15:29:07,604 - build - river - DEBUG - Derive river slope.


2021-09-01 15:29:08,265 - build - landuse - INFO - Deriving N_River using average resampling (nodata=-999.0).


2021-09-01 15:29:08,280 - build - wflow - DEBUG - Adding rivers vector to staticgeoms.


2021-09-01 15:29:08,807 - build - model_api - INFO - setup_reservoirs.reservoirs_fn: hydro_reservoirs
2021-09-01 15:29:08,807 - build - model_api - INFO - setup_reservoirs.min_area: 1.0
2021-09-01 15:29:08,807 - build - model_api - INFO - setup_reservoirs.priority_jrc: True
2021-09-01 15:29:08,807 - build - wflow - INFO - Preparing reservoir maps.
2021-09-01 15:29:08,808 - build - data_adapter - INFO - DataCatalog: Getting hydro_reservoirs GeoDataFrame vector data from /home/runner/.hydromt_data/data/v0.0.4/hydro_reservoirs.gpkg
2021-09-01 15:29:08,812 - build - data_adapter - INFO - GeoDataFrame: Read vector data and clip to geom (epsg:4326) [11.775, 45.804, 12.745, 46.690].


2021-09-01 15:29:08,862 - build - data_adapter - DEBUG - GeoDataFrame: Convert units for 5 columns.
2021-09-01 15:29:08,866 - build - wflow - WARNING - No reservoirs of sufficient size found within region! Skipping reservoir procedures!
2021-09-01 15:29:08,867 - build - model_api - INFO - setup_lakes.lakes_fn: hydro_lakes
2021-09-01 15:29:08,867 - build - model_api - INFO - setup_lakes.min_area: 1.0
2021-09-01 15:29:08,867 - build - wflow - INFO - Preparing lake maps.
2021-09-01 15:29:08,867 - build - data_adapter - INFO - DataCatalog: Getting hydro_lakes GeoDataFrame vector data from /home/runner/.hydromt_data/data/v0.0.4/hydro_lakes.gpkg
2021-09-01 15:29:08,872 - build - data_adapter - INFO - GeoDataFrame: Read vector data and clip to geom (epsg:4326) [11.775, 45.804, 12.745, 46.690].


2021-09-01 15:29:08,910 - build - data_adapter - DEBUG - GeoDataFrame: Convert units for 1 columns.
2021-09-01 15:29:08,913 - build - wflow - INFO - 1 lake(s) of sufficient size found within region.
2021-09-01 15:29:08,929 - build - waterbodies - DEBUG - Setting lake outlet map based maximum upstream area.


2021-09-01 15:29:09,000 - build - model_api - INFO - setup_riverwidth.predictor: discharge
2021-09-01 15:29:09,000 - build - model_api - INFO - setup_riverwidth.fill: False
2021-09-01 15:29:09,000 - build - model_api - INFO - setup_riverwidth.fit: False
2021-09-01 15:29:09,000 - build - model_api - INFO - setup_riverwidth.min_wth: 1
2021-09-01 15:29:09,000 - build - model_api - INFO - setup_riverwidth.precip_fn: chelsa
2021-09-01 15:29:09,000 - build - model_api - INFO - setup_riverwidth.climate_fn: koppen_geiger
2021-09-01 15:29:09,001 - build - data_adapter - INFO - DataCatalog: Getting chelsa RasterDataset raster data from /home/runner/.hydromt_data/data/v0.0.4/chelsa.tif
2021-09-01 15:29:09,018 - build - data_adapter - DEBUG - RasterDataset: Clip with geom - [11.778, 45.807, 12.745, 46.690]


2021-09-01 15:29:09,045 - build - data_adapter - INFO - DataCatalog: Getting koppen_geiger RasterDataset raster data from /home/runner/.hydromt_data/data/v0.0.4/koppen_geiger.tif
2021-09-01 15:29:09,062 - build - data_adapter - DEBUG - RasterDataset: Clip with geom - [11.778, 45.807, 12.745, 46.690]


2021-09-01 15:29:09,090 - build - river - DEBUG - Deriving predictor "discharge" values
2021-09-01 15:29:09,096 - build - river - DEBUG - Basin base climate classification: 3 (Cfb)


2021-09-01 15:29:09,151 - build - river - DEBUG - lakeareas masked out in rivwth data.
2021-09-01 15:29:09,151 - build - river - WARNING - mask variable "resareas" not found in maps.
2021-09-01 15:29:09,151 - build - river - WARNING - mask variable "glacareas" not found in maps.
2021-09-01 15:29:09,152 - build - river - INFO - Using "width = a*discharge^b"; where a=6.33, b=0.55 (nse=-0.450; outliers=4.66%)
2021-09-01 15:29:09,152 - build - river - INFO - rivwth set globally based on width-discharge relationship.
2021-09-01 15:29:09,155 - build - model_api - INFO - setup_riverbedsed.bedsed_mapping_fn: None
2021-09-01 15:29:09,155 - build - wflow_sediment - INFO - Preparing riverbedsed parameter maps.
2021-09-01 15:29:09,181 - build - landuse - INFO - Deriving D50_River using average resampling (nodata=-999.0).


2021-09-01 15:29:09,195 - build - landuse - INFO - Deriving ClayF_River using average resampling (nodata=-999.0).
2021-09-01 15:29:09,209 - build - landuse - INFO - Deriving SiltF_River using average resampling (nodata=-999.0).
2021-09-01 15:29:09,223 - build - landuse - INFO - Deriving SandF_River using average resampling (nodata=-999.0).
2021-09-01 15:29:09,237 - build - landuse - INFO - Deriving GravelF_River using average resampling (nodata=-999.0).


2021-09-01 15:29:09,259 - build - model_api - INFO - setup_lulcmaps.lulc_fn: globcover
2021-09-01 15:29:09,259 - build - model_api - INFO - setup_lulcmaps.lulc_mapping_fn: None
2021-09-01 15:29:09,259 - build - model_api - INFO - setup_lulcmaps.lulc_vars: ['landuse', 'Cov_River', 'Kext', 'N', 'PathFrac', 'Sl', 'Swood', 'USLE_C', 'WaterFrac']
2021-09-01 15:29:09,259 - build - wflow - INFO - Preparing LULC parameter maps.
2021-09-01 15:29:09,259 - build - data_adapter - INFO - DataCatalog: Getting globcover RasterDataset raster data from /home/runner/.hydromt_data/data/v0.0.4/globcover.tif
2021-09-01 15:29:09,277 - build - data_adapter - DEBUG - RasterDataset: Clip with geom - [11.778, 45.807, 12.745, 46.690]


2021-09-01 15:29:09,314 - build - landuse - INFO - Deriving landuse using nearest resampling (nodata=230).


2021-09-01 15:29:09,368 - build - landuse - INFO - Deriving Cov_River using average resampling (nodata=-999.0).


2021-09-01 15:29:09,418 - build - landuse - INFO - Deriving Kext using average resampling (nodata=-999.0).


2021-09-01 15:29:09,470 - build - landuse - INFO - Deriving N using average resampling (nodata=-999.0).


2021-09-01 15:29:09,522 - build - landuse - INFO - Deriving PathFrac using average resampling (nodata=-999.0).


2021-09-01 15:29:09,574 - build - landuse - INFO - Deriving Sl using average resampling (nodata=-999.0).


2021-09-01 15:29:09,627 - build - landuse - INFO - Deriving Swood using average resampling (nodata=-999.0).


2021-09-01 15:29:09,678 - build - landuse - INFO - Deriving USLE_C using average resampling (nodata=-999.0).


2021-09-01 15:29:09,730 - build - landuse - INFO - Deriving WaterFrac using average resampling (nodata=-999).


2021-09-01 15:29:09,798 - build - model_api - INFO - setup_laimaps.lai_fn: modis_lai
2021-09-01 15:29:09,798 - build - wflow - INFO - Preparing LAI maps.
2021-09-01 15:29:09,798 - build - data_adapter - INFO - DataCatalog: Getting modis_lai RasterDataset netcdf data from /home/runner/.hydromt_data/data/v0.0.4/modis_lai.nc


2021-09-01 15:29:09,818 - build - data_adapter - DEBUG - RasterDataset: Clip with geom - [11.778, 45.807, 12.745, 46.690]
2021-09-01 15:29:09,845 - build - data_adapter - DEBUG - RasterDataset: Convert units for 1 variables.
2021-09-01 15:29:09,854 - build - landuse - INFO - Deriving LAI using average resampling (nodata=None).


2021-09-01 15:29:09,935 - build - model_api - INFO - setup_canopymaps.canopy_fn: simard
2021-09-01 15:29:09,935 - build - wflow_sediment - INFO - Preparing canopy height map.
2021-09-01 15:29:09,935 - build - data_adapter - INFO - DataCatalog: Getting simard RasterDataset raster data from /home/runner/.hydromt_data/data/v0.0.4/simard.tif
2021-09-01 15:29:09,952 - build - data_adapter - DEBUG - RasterDataset: Clip with geom - [11.778, 45.807, 12.745, 46.690]


2021-09-01 15:29:10,013 - build - model_api - INFO - setup_soilmaps.soil_fn: soilgrids
2021-09-01 15:29:10,014 - build - model_api - INFO - setup_soilmaps.usleK_method: renard
2021-09-01 15:29:10,014 - build - wflow_sediment - INFO - Preparing soil parameter maps.
2021-09-01 15:29:10,014 - build - data_adapter - INFO - DataCatalog: Getting soilgrids RasterDataset raster data from /home/runner/.hydromt_data/data/v0.0.4/soilgrids/{variable}.tif


2021-09-01 15:29:10,415 - build - data_adapter - DEBUG - RasterDataset: Clip with geom - [11.778, 45.807, 12.745, 46.690]


2021-09-01 15:29:10,455 - build - data_adapter - DEBUG - RasterDataset: Convert units for 21 variables.


2021-09-01 15:29:11,830 - build - model_api - INFO - setup_gauges.gauges_fn: grdc
2021-09-01 15:29:11,830 - build - model_api - INFO - setup_gauges.source_gdf: None
2021-09-01 15:29:11,830 - build - model_api - INFO - setup_gauges.snap_to_river: True
2021-09-01 15:29:11,830 - build - model_api - INFO - setup_gauges.mask: None
2021-09-01 15:29:11,830 - build - model_api - INFO - setup_gauges.derive_subcatch: False
2021-09-01 15:29:11,830 - build - model_api - INFO - setup_gauges.derive_outlet: True
2021-09-01 15:29:11,830 - build - model_api - INFO - setup_gauges.basename: None
2021-09-01 15:29:11,830 - build - model_api - INFO - setup_gauges.update_toml: True
2021-09-01 15:29:11,830 - build - model_api - INFO - setup_gauges.gauge_toml_header: None
2021-09-01 15:29:11,831 - build - model_api - INFO - setup_gauges.gauge_toml_param: None
2021-09-01 15:29:11,831 - build - wflow - INFO - Gauges locations set based on river outlets.


2021-09-01 15:29:11,845 - build - wflow - INFO - Gauges map based on catchment river outlets added.
2021-09-01 15:29:11,846 - build - data_adapter - INFO - DataCatalog: Getting grdc GeoDataFrame csv data from /home/runner/.hydromt_data/data/v0.0.4/grdc.csv
2021-09-01 15:29:11,850 - build - data_adapter - INFO - GeoDataFrame: Read csv data and clip to geom (epsg:4326) [11.775, 45.804, 12.745, 46.690].
2021-09-01 15:29:11,876 - build - wflow - INFO - 3 grdc gauge locations found within domain
2021-09-01 15:29:11,891 - build - wflow - INFO - Gauges map from grdc added.


2021-09-01 15:29:11,913 - build - wflow - INFO - Write model data to /home/runner/work/hydromt_wflow/hydromt_wflow/docs/examples/examples/wflow_test_sediment
2021-09-01 15:29:11,913 - build - model_api - INFO - Writing model config to /home/runner/work/hydromt_wflow/hydromt_wflow/docs/examples/examples/wflow_test_sediment/wflow_sediment.toml
2021-09-01 15:29:11,914 - build - wflow - INFO - Write staticmaps to /home/runner/work/hydromt_wflow/hydromt_wflow/docs/examples/examples/wflow_test_sediment/staticmaps.nc


2021-09-01 15:29:12,362 - build - wflow - INFO - Writing model staticgeom to file.


The example above means the following: run **hydromt build** with:

* `wflow_sediment` : i.e. build a wflow sediment model
* `./wflow_test_sediment` : output model folder
* `"{'subbasin': [12.2051, 45.8331], 'strord': 4, 'bounds': [11.70, 45.35, 12.95, 46.70]}"` : derive a subbasin with its outlet at the given x,y coordinates and within the given bounds [xmin, ymin, xmax, ymax] (WGS84) snapped to a river with minimum stream order (strord) of 4. All *REGION* options are described in the [docs](https://deltares.github.io/hydromt/latest/user_guide/cli.html#region-options)
* `-r 0.0083333` : build the model at a 30 arc sec (~1km) resolution
* `-i wflow_sediment_build.ini` : setup configuration file using
* `-vv` : give some extra verbosity (2 * v) to display feedback on screen. Now debug messages are provided.


Next we check which files have been created. The model root should contain two netcdf (.nc) files, one for the staticmaps and one for the forcing data, a wflow configuration (.toml) file. These files are sufficient to run the wflow sediment model. In addition several geometry (.geojson) files are saved in the *staticgeoms* folder.  Finally, the setup process is logged in the hydromt.log file. 

In [5]:
import os
root = 'wflow_test_sediment'
for path, _, files in os.walk(root):
    print(path)
    for name in files:
        if name.endswith('.xml'):
            continue
        print(f' - {name}')

wflow_test_sediment
 - wflow_sediment.toml
 - hydromt.log
 - staticmaps.nc
wflow_test_sediment/setup
wflow_test_sediment/inmaps
wflow_test_sediment/staticmaps
wflow_test_sediment/run_default
wflow_test_sediment/staticgeoms
 - gauges.geojson
 - basins.geojson
 - gauges_grdc.geojson
 - lakes.geojson
 - rivers.geojson
 - region.geojson
wflow_test_sediment/instate


### Visualize and/or inspect model schematization

You can (copy and) adapt the following example notebooks in order to visualize your Wflow sediment model: 

* The **wflow plot** example notebook contains scripts to visualize your model
* The **wflow nc to raster files** example notebook contains scripts to write the nc model files to a netcdf which can be used to inspect (and modify) the model layers in e.g. QGIS.

### Add Wflow sediment layers to an existing Wflow model

If you already have a hydrological **Wflow** model and you want to extend it in order to include **sediment** as well, then you do not need to build the wflow_sediment from scratch. You can instead **update** the wflow model with the additional components needed by wflow_sediment. 

These components are available in the template **wflow_extend_sediment.ini**:

In [6]:
fn_ini = 'wflow_extend_sediment.ini'
with open(fn_ini, 'r') as f:
    txt = f.read()
print(txt)

[global]
data_libs        = []               # add optional paths to data yml files

[setup_config]
# model.dolake = True               # uncomment if there are lakes in the wflow model
# model.doreservoir = True          # uncomment if there are reservoirs in the wflow model

[setup_riverbedsed]
bedsed_mapping_fn   = None             # path to a mapping csv file from streamorder to river bed particles characteristics

[setup_lulcmaps]
lulc_fn          = globcover        # source for lulc maps: {globcover, vito, corine}

[setup_canopymaps]
canopy_fn        = simard           # source for vegetation canopy height: {simard}

[setup_soilmaps]
soil_fn          = soilgrids        # source for soilmaps: {soilgrids}
usleK_method     = renard           # method to compute the USLE K factor: {renard, epic}

[setup_gauges]
gauges_fn        = grdc             # If not None add gaugemap. Either a path or known gauges_fn: {grdc}
snap_to_river    = True             # If True snaps gauges from source

Let's update the hydrological **Wflow** model available from our example for the Piave subbasin:

In [7]:
# NOTE: copy this line (without !) to your shell for more direct feedback
!hydromt update wflow_sediment "wflow_piave_subbasin" -o "./wflow_test_extend_sediment" -i wflow_extend_sediment.ini -vv

2021-09-01 15:29:15,753 - update - log - DEBUG - Writing log messages to new file /home/runner/work/hydromt_wflow/hydromt_wflow/docs/examples/examples/wflow_test_extend_sediment/hydromt.log.
2021-09-01 15:29:15,754 - update - log - INFO - HydroMT version: 0.4.3.dev
2021-09-01 15:29:15,754 - update - main - INFO - Updating wflow_sediment model at /home/runner/work/hydromt_wflow/hydromt_wflow/docs/examples/examples/wflow_piave_subbasin (r).
2021-09-01 15:29:15,754 - update - main - INFO - Output dir: /home/runner/work/hydromt_wflow/hydromt_wflow/docs/examples/examples/wflow_test_extend_sediment
2021-09-01 15:29:15,754 - update - main - INFO - User settings:


2021-09-01 15:29:15,796 - update - model_plugins - DEBUG - Loaded model plugin 'wflow_sediment = hydromt_wflow.wflow_sediment.WflowSedimentModel' (0.1.2)
2021-09-01 15:29:15,796 - update - model_api - INFO - Initializing wflow_sediment model from hydromt_wflow (v0.1.2).
2021-09-01 15:29:15,797 - update - model_api - ERROR - Model config file not found at /home/runner/work/hydromt_wflow/hydromt_wflow/docs/examples/examples/wflow_piave_subbasin/wflow_sediment.toml
2021-09-01 15:29:15,797 - update - model_api - ERROR - Model config file not found at /home/runner/work/hydromt_wflow/hydromt_wflow/docs/examples/examples/wflow_piave_subbasin/wflow_sediment.toml
2021-09-01 15:29:15,797 - update - wflow - INFO - Read staticmaps from /home/runner/work/hydromt_wflow/hydromt_wflow/docs/examples/examples/wflow_piave_subbasin/staticmaps.nc


2021-09-01 15:29:15,868 - update - wflow - INFO - Reading model intbl files.
2021-09-01 15:29:15,868 - update - model_api - ERROR - Model config file not found at /home/runner/work/hydromt_wflow/hydromt_wflow/docs/examples/examples/wflow_piave_subbasin/wflow_sediment.toml
2021-09-01 15:29:15,868 - update - wflow - INFO - Reading model staticgeom files.


2021-09-01 15:29:16,057 - update - model_api - ERROR - Model config file not found at /home/runner/work/hydromt_wflow/hydromt_wflow/docs/examples/examples/wflow_piave_subbasin/wflow_sediment.toml
2021-09-01 15:29:16,057 - update - wflow - INFO - Read forcing from /home/runner/work/hydromt_wflow/hydromt_wflow/docs/examples/examples/wflow_piave_subbasin/inmaps.nc
2021-09-01 15:29:16,069 - update - wflow - INFO - Model read


2021-09-01 15:29:16,081 - update - model_api - INFO - setup_riverbedsed.bedsed_mapping_fn: None
2021-09-01 15:29:16,081 - update - wflow_sediment - INFO - Preparing riverbedsed parameter maps.
2021-09-01 15:29:16,097 - update - landuse - INFO - Deriving D50_River using average resampling (nodata=-999.0).
2021-09-01 15:29:16,110 - update - landuse - INFO - Deriving ClayF_River using average resampling (nodata=-999.0).
2021-09-01 15:29:16,123 - update - landuse - INFO - Deriving SiltF_River using average resampling (nodata=-999.0).


2021-09-01 15:29:16,137 - update - landuse - INFO - Deriving SandF_River using average resampling (nodata=-999.0).
2021-09-01 15:29:16,150 - update - landuse - INFO - Deriving GravelF_River using average resampling (nodata=-999.0).


2021-09-01 15:29:16,183 - update - model_api - INFO - setup_lulcmaps.lulc_fn: globcover
2021-09-01 15:29:16,183 - update - model_api - INFO - setup_lulcmaps.lulc_mapping_fn: None
2021-09-01 15:29:16,183 - update - model_api - INFO - setup_lulcmaps.lulc_vars: ['landuse', 'Cov_River', 'Kext', 'N', 'PathFrac', 'Sl', 'Swood', 'USLE_C', 'WaterFrac']
2021-09-01 15:29:16,183 - update - wflow - INFO - Preparing LULC parameter maps.
2021-09-01 15:29:16,194 - update - data_adapter - INFO - Updating data sources from yml file /home/runner/.hydromt_data/data/v0.0.4/data_catalog.yml


2021-09-01 15:29:16,275 - update - data_adapter - INFO - DataCatalog: Getting globcover RasterDataset raster data from /home/runner/.hydromt_data/data/v0.0.4/globcover.tif


2021-09-01 15:29:16,304 - update - data_adapter - DEBUG - RasterDataset: Clip with geom - [11.775, 45.808, 12.742, 46.692]


2021-09-01 15:29:16,341 - update - landuse - INFO - Deriving landuse using nearest resampling (nodata=230).


2021-09-01 15:29:16,394 - update - landuse - INFO - Deriving Cov_River using average resampling (nodata=-999.0).


2021-09-01 15:29:16,446 - update - landuse - INFO - Deriving Kext using average resampling (nodata=-999.0).


2021-09-01 15:29:16,497 - update - landuse - INFO - Deriving N using average resampling (nodata=-999.0).


2021-09-01 15:29:16,549 - update - landuse - INFO - Deriving PathFrac using average resampling (nodata=-999.0).


2021-09-01 15:29:16,600 - update - landuse - INFO - Deriving Sl using average resampling (nodata=-999.0).


2021-09-01 15:29:16,651 - update - landuse - INFO - Deriving Swood using average resampling (nodata=-999.0).


2021-09-01 15:29:16,702 - update - landuse - INFO - Deriving USLE_C using average resampling (nodata=-999.0).


2021-09-01 15:29:16,754 - update - landuse - INFO - Deriving WaterFrac using average resampling (nodata=-999).


2021-09-01 15:29:16,842 - update - model_api - INFO - setup_canopymaps.canopy_fn: simard
2021-09-01 15:29:16,842 - update - wflow_sediment - INFO - Preparing canopy height map.


2021-09-01 15:29:16,853 - update - data_adapter - INFO - DataCatalog: Getting simard RasterDataset raster data from /home/runner/.hydromt_data/data/v0.0.4/simard.tif
2021-09-01 15:29:16,869 - update - data_adapter - DEBUG - RasterDataset: Clip with geom - [11.775, 45.808, 12.742, 46.692]


2021-09-01 15:29:16,934 - update - model_api - INFO - setup_soilmaps.soil_fn: soilgrids
2021-09-01 15:29:16,934 - update - model_api - INFO - setup_soilmaps.usleK_method: renard
2021-09-01 15:29:16,934 - update - wflow_sediment - INFO - Preparing soil parameter maps.


2021-09-01 15:29:16,945 - update - data_adapter - INFO - DataCatalog: Getting soilgrids RasterDataset raster data from /home/runner/.hydromt_data/data/v0.0.4/soilgrids/{variable}.tif


2021-09-01 15:29:17,319 - update - data_adapter - DEBUG - RasterDataset: Clip with geom - [11.775, 45.808, 12.742, 46.692]


2021-09-01 15:29:17,358 - update - data_adapter - DEBUG - RasterDataset: Convert units for 21 variables.


2021-09-01 15:29:18,731 - update - model_api - INFO - setup_gauges.gauges_fn: grdc
2021-09-01 15:29:18,731 - update - model_api - INFO - setup_gauges.source_gdf: None
2021-09-01 15:29:18,731 - update - model_api - INFO - setup_gauges.snap_to_river: True
2021-09-01 15:29:18,731 - update - model_api - INFO - setup_gauges.mask: None
2021-09-01 15:29:18,731 - update - model_api - INFO - setup_gauges.derive_subcatch: False
2021-09-01 15:29:18,731 - update - model_api - INFO - setup_gauges.derive_outlet: True
2021-09-01 15:29:18,731 - update - model_api - INFO - setup_gauges.basename: None
2021-09-01 15:29:18,731 - update - model_api - INFO - setup_gauges.update_toml: True
2021-09-01 15:29:18,731 - update - model_api - INFO - setup_gauges.gauge_toml_header: None
2021-09-01 15:29:18,732 - update - model_api - INFO - setup_gauges.gauge_toml_param: None
2021-09-01 15:29:18,732 - update - wflow - INFO - Gauges locations set based on river outlets.


2021-09-01 15:29:19,694 - update - wflow - INFO - Gauges map based on catchment river outlets added.
2021-09-01 15:29:19,694 - update - data_adapter - INFO - DataCatalog: Getting grdc GeoDataFrame csv data from /home/runner/.hydromt_data/data/v0.0.4/grdc.csv
2021-09-01 15:29:19,699 - update - data_adapter - INFO - GeoDataFrame: Read csv data and clip to geom (epsg:4326) [11.775, 45.804, 12.745, 46.690].
2021-09-01 15:29:19,725 - update - wflow - INFO - 3 grdc gauge locations found within domain


2021-09-01 15:29:20,581 - update - model_api - DEBUG - Default config read from /usr/share/miniconda/envs/hydromt-wflow/lib/python3.9/site-packages/hydromt_wflow/data/wflow_sediment/wflow_sediment.toml
2021-09-01 15:29:20,581 - update - wflow - INFO - Gauges map from grdc added.


2021-09-01 15:29:20,615 - update - wflow - INFO - Write model data to /home/runner/work/hydromt_wflow/hydromt_wflow/docs/examples/examples/wflow_test_extend_sediment
2021-09-01 15:29:20,615 - update - model_api - INFO - Writing model config to /home/runner/work/hydromt_wflow/hydromt_wflow/docs/examples/examples/wflow_test_extend_sediment/wflow_sediment.toml
2021-09-01 15:29:20,616 - update - wflow - INFO - Write staticmaps to /home/runner/work/hydromt_wflow/hydromt_wflow/docs/examples/examples/wflow_test_extend_sediment/staticmaps.nc


2021-09-01 15:29:21,511 - update - wflow - INFO - Writing model staticgeom to file.


2021-09-01 15:29:21,730 - update - wflow - INFO - Write forcing file
2021-09-01 15:29:21,749 - update - wflow - INFO - Process forcing; saving to /home/runner/work/hydromt_wflow/hydromt_wflow/docs/examples/examples/wflow_test_extend_sediment/inmaps.nc
[                                        ] | 0% Completed |  0.0s

[########################################] | 100% Completed |  0.1s


The example above means the following: run **hydromt update** with:

* `wflow_sediment` : i.e. update a wflow_sediment model (in our case a wflow model but with wflow_sediment components)
* `wflow_piave_subbasin` : hydrological wflow model folder
* `-o "./wflow_test_extend_sediment"`: output combined wflow hydrology+sediment models
* `-i wflow_extend_sediment.ini` : setup configuration file containing wflow sediment specific components
* `-vv` : give some extra verbosity (2 * v) to display feedback on screen. Now debug messages are provided.