name: Build Documentation

on:
  workflow_dispatch:
  push:
    branches: [main, release/**, feat/private-docs]
    paths:
      - docs/**
      - examples/**
      - hydromt_wflow/**
      - pyproject.toml
      - .github/workflows/docs.yml
  pull_request:
    branches: [main, release/**, feat/private-docs]
    paths:
      - docs/**
      - examples/**
      - hydromt_wflow/**
      - pyproject.toml
      - .github/workflows/docs.yml

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs:
    defaults:
      run:
        shell: bash -l {0}
    env:
      branch_name: ${{ github.head_ref || github.ref_name }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v6

      - name: Setup pixi env
        uses: prefix-dev/setup-pixi@v0.9.3
        with:
          pixi-version: "v0.59.0"
          environments: docs
          locked: false
          cache: true

      - name: Generate dummy docs
        if: ${{ github.event_name == 'pull_request' &&  !startsWith(github.ref_name, 'feat/private-docs') }}
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: pixi run --locked -e docs docs-build-dummy

      - name: Generate docs
        if: ${{ github.event_name != 'pull_request' && !github.event.act &&  !startsWith(github.ref_name, 'feat/private-docs') }}
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: |
            pixi run -e docs docs-build-html

            export CURRENT_VERSION=$(grep "__version__" hydromt_wflow/version.py | cut -d= -f 2 | tr -d "\" ")

            if [ -z "$CURRENT_VERSION" ]; then
              echo "Could not determine version, exiting..."
              exit 1
            fi

            if echo "$CURRENT_VERSION" | grep -q "dev"; then
              echo "DOC_VERSION=dev" >> "$GITHUB_ENV"
            else
              echo "DOC_VERSION=v$CURRENT_VERSION" >> "$GITHUB_ENV"
            fi

      - name: Prepare versioned docs directory
        if: ${{ github.event_name != 'pull_request' && !startsWith(github.ref_name, 'feat/private-docs') }}
        run: |
          rm -rf site/${DOC_VERSION}
          mkdir -p site/${DOC_VERSION}
          cp -r docs/_build/html/* site/${DOC_VERSION}/

      - name: Setup Pages
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-pages-artifact@v4
        with:
          path: site/

      - name: Deploy to GitHub Pages
        if: ${{ github.event_name != 'pull_request' }}
        id: deployment
        uses: actions/deploy-pages@v4
