name: Build Documentation

on:
  workflow_dispatch:
  push:
    branches: [main, release/**]
    paths:
      - docs/**
      - examples/**
      - hydromt_wflow/**
      - pyproject.toml
      - .github/workflows/docs.yml
  pull_request:
    branches: [main, release/**]
    paths:
      - docs/**
      - examples/**
      - hydromt_wflow/**
      - pyproject.toml
      - .github/workflows/docs.yml

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs:
    concurrency:
      group: docs-${{ github.ref_name }}
      cancel-in-progress: true

    defaults:
      run:
        shell: bash -l {0}
    env:
      branch_name: ${{ github.head_ref || github.ref_name }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v6

      - name: Setup pixi env
        uses: prefix-dev/setup-pixi@v0.9.3
        with:
          pixi-version: "v0.59.0"
          environments: docs
          locked: false
          cache: true

      - name: Extract version
        run: |
          export CURRENT_VERSION=$(grep "__version__" hydromt_wflow/version.py | cut -d= -f 2 | tr -d "\" ")

          if [ -z "$CURRENT_VERSION" ]; then
            echo "Could not determine version, exiting..."
            exit 1
          fi

          if echo "$CURRENT_VERSION" | grep -q "dev"; then
            DOC_VERSION=dev
          else
            DOC_VERSION="v$CURRENT_VERSION"
          fi

          echo "Extracted docs version: $DOC_VERSION" 
          echo "DOC_VERSION=$DOC_VERSION" >> "$GITHUB_ENV"

      - name: Check switcher.json for release version
        if: ${{ env.DOC_VERSION != 'dev' }}
        run: |
          SWITCHER_JSON=docs/_static/switcher.json

          if [ ! -f "$SWITCHER_JSON" ]; then
            echo "Error: switcher.json not found at $SWITCHER_JSON"
            exit 1
          fi

          # Check if the current release version exists
          if ! jq --arg ver "${DOC_VERSION}" 'any(.[]; .version==$ver)' "$SWITCHER_JSON" | grep -q true; then
            echo "Error: Release version ${DOC_VERSION} is not present in $SWITCHER_JSON.\n"
            echo "Add it to the list of released versions using the base url 'https://fluffy-happiness-gzowznm.pages.github.io/' and re-run this workflow."
            exit 1
          fi

      - name: Generate dummy docs
        if: ${{ github.event_name == 'pull_request' }}
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: pixi run --locked -e docs docs-build-dummy

      - name: Generate docs
        if: ${{ github.event_name != 'pull_request' && !github.event.act }}
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: pixi run --locked -e docs docs-build-html

      - name: Prepare versioned docs directory
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          rm -rf site/${DOC_VERSION}
          mkdir -p site/${DOC_VERSION}
          cp -r docs/_build/html/* site/${DOC_VERSION}/

          if [ "${DOC_VERSION}" = "dev" ]; then
            # dev version: update /latest alias
            rm -rf site/latest
            mkdir -p site/latest
            cp -r site/${DOC_VERSION}/* site/latest/
          else
            # release version: update /stable alias
            rm -rf site/stable
            mkdir -p site/stable
            cp -r site/${DOC_VERSION}/* site/stable/
          fi

      - name: Setup Pages
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-pages-artifact@v4
        with:
          path: site/

      - name: Deploy to GitHub Pages
        if: ${{ github.event_name != 'pull_request' }}
        id: deployment
        uses: actions/deploy-pages@v4
