name: Record new benchmark

on:
  workflow_dispatch:


jobs:
  test:
    defaults:
      run:
        shell: bash -l {0}
    name: Record benchmark
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pixi env
        uses: prefix-dev/setup-pixi@v0.8.14
        with:
          pixi-version: "v0.45.0"
          environments: test-full-py311
          locked: false
          cache: true

      - name: Tests
        run: |
            pixi run -e test-full-py311 benchmark-record

            git checkout -b "chore/record-benchmark"
            git config user.name "GitHub Actions Bot"
            git config user.email "<>"
            git add .benchmark
            git commit -m "record benchmark"
            git push --set-upstream origin "chore/record-benchmark"

            gh pr create -B "main" -H "chore/record-benchmark" -t "Record new benchmark" -b "This is an automated PR to add benchmark timings"
