name: SonarQube Scan and coverage

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - v1
    paths:
      - tests/**/*
      - hydromt_wflow/**/*
      - data/**/*
      - pyproject.toml
      - pixi.lock
      - .github/workflows/sonar.yml
      - sonar-project.properties
  pull_request:
    branches:
      - main
      - v1
    paths:
      - tests/**/*
      - hydromt_wflow/**/*
      - data/**/*
      - pyproject.toml
      - pixi.lock
      - .github/workflows/sonar.yml
      - sonar-project.properties
  workflow_run:
    workflows: [Pixi auto update]
    types:
      - completed


jobs:
  scan:
    defaults:
      run:
        shell: bash -e -l {0}

    name: run test coverage and SonarQube scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.0
        with:
          pixi-version: "v0.47.0"
      - name: Run the test suite
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: |
            pixi run --locked -e test-full-py311 test-cov
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
