name: Test conda forge release

on:
  schedule:
  # At 00:00 UTC every Monday
    - cron: "0 0 * * 1"
  # on demand
  workflow_dispatch:

jobs:
  Test:
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest" ] #, "macos-latest", "windows-latest"]
        python-version: ['3.11']
        include:
        - os: ubuntu-latest
          label: linux-64
          prefix: /usr/share/miniconda3/envs/hydromt_wflow

    name: ${{ matrix.label }} - py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.python-version }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: hydromt-wflow

      - name: Install hydromt_wflow
        run: mamba install -c conda-forge hydromt_wflow

      - name: Install test dependencies
        run: |
          mamba install -c conda-forge pytest pytest-cov pytest-mock pytest-timeout
          pip install gwwapi

      - name: Conda info
        run: |
         conda info
         conda list

      - name: Run model build Tests
        run: python -m pytest --verbose tests/test_model_class.py::test_model_build
